/**
 * The route-template save path, transport-neutral.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS FILE EXISTS
 * ---------------------------------------------------------------------------
 * All of this was the body of the `saveRouteTemplate` server action, and the
 * action is now a ten-line wrapper over it. It was LIFTED, not copied: the
 * validation order, the messages, the transaction shape and the delete-then-
 * recreate edit strategy are the same code, so there is exactly one place a
 * template gets written and Phase 6 cannot drift away from what the Templates
 * screen does.
 *
 * The move was forced by two things the action could not do:
 *
 *  1. **`getSession()` is a cookie read.** Document import runs on both surfaces
 *     and the mobile one authenticates with a Bearer token — there is no session
 *     cookie and no `x-tenant-id` header on `/api/mobile/*` (DEC-11). A server
 *     action is reachable from the browser only.
 *  2. **`getTenantPrisma()` reads that same header.** Header-less callers need
 *     `getTenantPrismaForOrg(orgId, userId)`, so the client has to be a parameter
 *     rather than something the function fetches for itself.
 *
 * The same shape Phase 4 used when it needed `createFacility` from a header-less
 * context: the existing function gained an optional pre-resolved client and two
 * optional audit fields, and every existing call site is byte-identical in
 * behaviour.
 */

import { prisma } from '@/lib/db/prisma'; // kept for $transaction — see below
import type { PrismaClient } from '@/generated/prisma';

/** One stop as the Templates screen's stop builder produces it. */
export interface SaveRouteTemplateStop {
  facility_id: string | null;
  sequence_order: number;
  stop_type: string;
  contact_name?: string | null;
  contact_phone?: string | null;
  appt_window_start_offset_min?: number | null;
  appt_window_end_offset_min?: number | null;
  expected_dwell_minutes?: number | null;
  commodity_description?: string | null;
  bol_required?: boolean;
  pod_required?: boolean;
  special_instructions?: string | null;
}

export interface SaveRouteTemplateCore {
  templateId?: string;
  templateName: string;
  clientId: string;
  contractId?: string;
  scheduleType: string;
  recurrenceRule?: string;
  recurrenceTimezone?: string;
  scheduledDepartureTime?: string;
  equipmentType: string;
  tempMinF?: number;
  tempMaxF?: number;
  maxWeightLbs?: number;
  commodityDescription?: string;
  defaultDriverId?: string;
  defaultTruckId?: string;
  autoGenerateDaysAhead?: number;
  notes?: string;
  stops: SaveRouteTemplateStop[];

  // ---- Additive, and omitting them is the previous behaviour exactly --------
  /**
   * The import this template was created from (spec Section 8: *"Auto-created
   * templates carry the source import reference"*). Also set for a human's
   * one-tap "Save as route template", because the reference describes where the
   * row came from and that is true either way — what separates the two is
   * `isSuggested`, which is about whether a human has confirmed it.
   */
  sourceImportId?: string;
  /** Lands the template in "Suggested templates" until a human confirms it. */
  isSuggested?: boolean;
  createdById?: string;
  /**
   * This route's end stop override — the SECOND rung of spec Section 9's
   * "tenant default, then template override, then per-trip choice".
   *
   * `route_templates.end_stop_policy` is nullable, and null is meaningful: it
   * says "this route has no opinion, use the company default". So an omitted
   * field leaves the column exactly as it was, and passing `null` explicitly is
   * how a caller clears an override — the same distinction between "not
   * mentioned" and "clear it" that the stop-review patch draws.
   *
   * The value is checked against the CHECK constraint's five below rather than
   * trusted. TypeScript sees a `String` column; Postgres sees
   * `dispatches_end_stop_policy_check`, and the gap between those two is where a
   * 23514 lives (DEC-14).
   */
  endStopPolicy?: string | null;
  /**
   * Where the truck parks when this route's policy is `DESIGNATED_PARKING` —
   * `route_templates.end_stop_facility_id`.
   *
   * Same `undefined` / `null` distinction as `endStopPolicy` above: an omitted
   * field leaves the column exactly as it was, and an explicit `null` clears it.
   * That is what keeps every existing caller byte-identical, and it is what stops
   * a reorder or an auto-create from wiping a facility it never mentioned.
   *
   * **Validated rather than trusted.** This is a raw uuid arriving from a form,
   * and the three things it could be — another tenant's facility, a deactivated
   * one, or a driver's home address — are all things the database's FK will
   * happily accept. Only the ladder's rules can reject them.
   */
  endStopFacilityId?: string | null;
}

/**
 * `route_templates_end_stop_policy_check`, read from `pg_constraint` on
 * 2026-08-10. Restated here rather than imported from
 * `lib/document-import/end-stop-constants.ts` because this file predates that
 * module and belongs to the carrier layer, which must not depend on a feature
 * module. A test pins the two lists together.
 */
const END_STOP_POLICIES: readonly string[] = [
  'RETURN_TO_ORIGIN',
  'HOME_BASE',
  'DESIGNATED_PARKING',
  'DRIVER_RESIDENCE',
  'NONE',
];

export interface SaveRouteTemplateOutcome {
  success: boolean;
  templateId?: string;
  error?: string;
}

/**
 * Validate and write a route template and its stops.
 *
 * `db` is the tenant-scoped client used for every ownership check;
 * `prisma.$transaction` is used for the write itself, which is what the action
 * did before this file existed. The comment it carried — *"kept for
 * $transaction"* — is the reason: the RLS extension wraps model operations, and
 * the interactive transaction is opened on the base client so the two statements
 * land together. Every `where` inside it still carries `orgId` explicitly, which
 * is what tenant isolation actually rests on here (DEC-11).
 */
export async function saveRouteTemplateCore(
  db: PrismaClient,
  orgId: string,
  data: SaveRouteTemplateCore,
): Promise<SaveRouteTemplateOutcome> {
  const {
    templateId,
    templateName,
    clientId,
    contractId,
    scheduleType,
    recurrenceRule,
    recurrenceTimezone,
    scheduledDepartureTime,
    equipmentType,
    tempMinF,
    tempMaxF,
    maxWeightLbs,
    commodityDescription,
    defaultDriverId,
    defaultTruckId,
    autoGenerateDaysAhead,
    notes,
    stops,
    sourceImportId,
    isSuggested,
    createdById,
    endStopPolicy,
    endStopFacilityId,
  } = data;

  // Validate required fields
  if (!templateName.trim()) return { success: false, error: 'Template name is required' };
  if (!clientId) return { success: false, error: 'Client is required' };
  if (!equipmentType) return { success: false, error: 'Equipment type is required' };
  if (!scheduleType) return { success: false, error: 'Schedule type is required' };
  if (recurrenceRule && !recurrenceRule.startsWith('FREQ=')) {
    return { success: false, error: 'Recurrence rule must start with FREQ=' };
  }
  if (stops.length === 0) return { success: false, error: 'At least one stop is required' };
  if (stops.some((s) => !s.facility_id)) {
    return { success: false, error: 'All stops must have a facility selected.' };
  }
  // Rejected here rather than thrown by Postgres as a 23514 nobody can act on.
  if (endStopPolicy != null && !END_STOP_POLICIES.includes(endStopPolicy)) {
    return { success: false, error: 'That is not an end stop this system has.' };
  }

  // Verify clientId belongs to this org
  const client = await db.carrierClient.findFirst({
    where: { id: clientId, orgId },
    select: { id: true },
  });
  if (!client) {
    return { success: false, error: 'Invalid client — does not belong to this organization' };
  }

  // Verify contractId if supplied
  if (contractId) {
    const contract = await db.carrierContract.findFirst({
      where: { id: contractId, orgId },
      select: { id: true },
    });
    if (!contract) {
      return { success: false, error: 'Invalid contract — does not belong to this organization' };
    }
  }

  // Verify defaultDriverId if supplied
  if (defaultDriverId) {
    const driver = await db.carrierDriver.findFirst({
      where: { id: defaultDriverId, orgId },
      select: { id: true },
    });
    if (!driver) {
      return { success: false, error: 'Invalid driver — does not belong to this organization' };
    }
  }

  // Verify defaultTruckId if supplied
  if (defaultTruckId) {
    const truck = await db.carrierTruck.findFirst({
      where: { id: defaultTruckId, orgId },
      select: { id: true },
    });
    if (!truck) {
      return { success: false, error: 'Invalid truck — does not belong to this organization' };
    }
  }

  // Verify all stop facilityIds belong to this org (batch check)
  const facilityIds = [...new Set(stops.map((s) => s.facility_id).filter(Boolean))] as string[];
  if (facilityIds.length > 0) {
    const validFacilities = await db.carrierFacility.findMany({
      where: { id: { in: facilityIds }, orgId },
      select: { id: true },
    });
    const validFacilityIds = new Set(validFacilities.map((f) => f.id));
    const invalidFacility = facilityIds.find((id) => !validFacilityIds.has(id));
    if (invalidFacility) {
      return { success: false, error: 'Invalid facility — does not belong to this organization' };
    }
  }

  // ---- The designated-parking facility -------------------------------------
  // `undefined` = not mentioned = leave the column alone. Anything else is
  // resolved into this and spread in at the bottom.
  let endStopFacilityUpdate: string | null | undefined = undefined;

  if (typeof endStopFacilityId === 'string' && endStopFacilityId.length > 0) {
    // The policy must arrive in the SAME payload. Deliberately not resolved by
    // reading the existing row first: every caller that sets a facility also
    // states the policy (the form sends both; the reorder path carries both
    // through), so a second read would only exist to let a caller be vague about
    // a decision it has already made.
    if (endStopPolicy !== 'DESIGNATED_PARKING') {
      return { success: false, error: 'Only designated parking takes a facility.' };
    }

    const facility = await db.carrierFacility.findFirst({
      where: {
        id: endStopFacilityId,
        orgId,
        NOT: { facilityType: { startsWith: 'inactive_' } },
      },
      select: { id: true, isDriverResidence: true },
    });
    if (!facility) {
      return { success: false, error: 'That facility is not available.' };
    }
    // A residence is never designated parking, whoever is asking — the same rule
    // and the same sentence as `setEndStopChoice`. This core has no `viewer`, so
    // the check is unconditional: `residenceFacilityForDriver` guards the LOOKUP,
    // and this guards the WRITE, which is the division that service documents.
    if (facility.isDriverResidence) {
      return {
        success: false,
        error: 'A driver’s home cannot be designated parking. Choose the driver’s home policy instead.',
      };
    }

    endStopFacilityUpdate = facility.id;
  } else if (endStopFacilityId === null) {
    endStopFacilityUpdate = null;
  }

  // And regardless of the above: writing the policy to anything other than
  // `DESIGNATED_PARKING` clears the facility. A template must not carry a
  // parking spot its own policy will never read — a value nothing reads is a
  // value that comes back to life the next time somebody flips the policy.
  if (endStopPolicy !== undefined && endStopPolicy !== 'DESIGNATED_PARKING') {
    endStopFacilityUpdate = null;
  }

  // Build template payload — only include optional fields if set
  const templateData = {
    templateName: templateName.trim(),
    clientId,
    scheduleType,
    equipmentType,
    ...(contractId ? { contractId } : {}),
    ...(recurrenceRule ? { recurrenceRule } : {}),
    ...(recurrenceTimezone ? { recurrenceTimezone } : {}),
    ...(scheduledDepartureTime ? { scheduledDepartureTime } : {}),
    ...(tempMinF != null ? { tempMinF } : {}),
    ...(tempMaxF != null ? { tempMaxF } : {}),
    ...(maxWeightLbs != null ? { maxWeightLbs } : {}),
    ...(commodityDescription ? { commodityDescription } : {}),
    ...(defaultDriverId ? { defaultDriverId } : {}),
    ...(defaultTruckId ? { defaultTruckId } : {}),
    ...(autoGenerateDaysAhead != null ? { autoGenerateDaysAhead } : {}),
    ...(notes ? { notes } : {}),
    ...(sourceImportId ? { sourceImportId } : {}),
    ...(isSuggested != null ? { isSuggested } : {}),
    // `undefined` leaves the column alone; an explicit `null` clears the
    // override. See the field's comment — the two are different requests.
    ...(endStopPolicy !== undefined ? { endStopPolicy } : {}),
    ...(endStopFacilityUpdate !== undefined ? { endStopFacilityId: endStopFacilityUpdate } : {}),
  };

  // Map the stop builder's shape → RouteTemplateStop DB fields
  const stopData = stops.map((stop) => ({
    facilityId: stop.facility_id as string,
    sequenceOrder: stop.sequence_order,
    stopType: stop.stop_type,
    contactName: stop.contact_name ?? null,
    contactPhone: stop.contact_phone ?? null,
    apptWindowStartOffsetMin: stop.appt_window_start_offset_min ?? null,
    apptWindowEndOffsetMin: stop.appt_window_end_offset_min ?? null,
    expectedDwellMinutes: stop.expected_dwell_minutes ?? null,
    commodityDescription: stop.commodity_description ?? null,
    bolRequired: stop.bol_required ?? true,
    podRequired: stop.pod_required ?? true,
    specialInstructions: stop.special_instructions ?? null,
    ...(createdById ? { createdById } : {}),
  }));

  if (templateId) {
    // Edit mode: update template + replace stops in a single transaction
    // (ownership check and update are atomic to prevent TOCTOU).
    const notFound = await prisma.$transaction(async (tx) => {
      const existing = await tx.routeTemplate.findFirst({ where: { id: templateId, orgId } });
      if (!existing) return true;

      await tx.routeTemplate.update({
        where: { id: templateId },
        data: { ...templateData, ...(createdById ? { updatedById: createdById } : {}) },
      });
      await tx.routeTemplateStop.deleteMany({ where: { routeTemplateId: templateId } });
      for (const s of stopData) {
        await tx.routeTemplateStop.create({
          data: { routeTemplateId: templateId, ...s },
        });
      }
      return false;
    });

    if (notFound) return { success: false, error: 'Template not found' };

    return { success: true, templateId };
  }

  // Create mode: create template then stops in a transaction
  const result = await prisma.$transaction(async (tx) => {
    const template = await tx.routeTemplate.create({
      data: {
        orgId,
        ...templateData,
        ...(createdById ? { createdById, updatedById: createdById } : {}),
      },
    });

    if (stopData.length > 0) {
      await tx.routeTemplateStop.createMany({
        data: stopData.map((s) => ({ routeTemplateId: template.id, ...s })),
      });
    }

    return template;
  });

  return { success: true, templateId: result.id };
}
