import { getTenantPrisma } from '@/lib/context/tenant-context';
import { logger } from '@/lib/logger';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ListRouteTemplatesFilters {
  clientId?: string;
  contractId?: string;
  active?: boolean;
  search?: string;
  page?: number;
  pageSize?: number;
}

export interface RouteTemplateCreateInput {
  templateName: string;
  clientId: string;
  contractId?: string;
  scheduleType: string;
  recurrenceRule?: string;
  recurrenceTimezone?: string;
  scheduledDepartureTime?: string;
  equipmentType: string;
  tempMinF?: number;
  tempMaxF?: number;
  maxWeightLbs?: number;
  commodityDescription?: string;
  estimatedMiles?: number;
  defaultDriverId?: string;
  defaultTruckId?: string;
  autoGenerateDaysAhead?: number;
  notes?: string;
}

export type RouteTemplateUpdateInput = Partial<RouteTemplateCreateInput> & { active?: boolean };

// ---------------------------------------------------------------------------
// Helper: Parse RRULE and compute next occurrence date
// ---------------------------------------------------------------------------

/**
 * Compute the next occurrence date from today given an iCal RRULE string.
 * Supports:
 *   FREQ=DAILY;INTERVAL=N
 *   FREQ=WEEKLY;BYDAY=MO,WE,FR;INTERVAL=N
 *   FREQ=MONTHLY;BYMONTHDAY=1,15;INTERVAL=N
 * Returns ISO date string (YYYY-MM-DD) or null if exhausted/unparseable.
 */
export function computeNextOccurrence(recurrenceRule: string, timezone: string): string | null {
  try {
    const parts: Record<string, string> = {};
    for (const segment of recurrenceRule.split(';')) {
      const eq = segment.indexOf('=');
      if (eq === -1) continue;
      parts[segment.slice(0, eq).toUpperCase()] = segment.slice(eq + 1);
    }

    const freq = parts['FREQ'];
    if (!freq) return null;

    const interval = parseInt(parts['INTERVAL'] ?? '1', 10);
    const until = parts['UNTIL'] ? parts['UNTIL'].slice(0, 8) : null; // YYYYMMDD
    const countMax = parts['COUNT'] ? parseInt(parts['COUNT'], 10) : null;

    // Work from today in the specified timezone (approximate — use local date)
    const now = new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

    const DAY_MAP: Record<string, number> = {
      SU: 0, MO: 1, TU: 2, WE: 3, TH: 4, FR: 5, SA: 6,
    };

    let count = 0;

    if (freq === 'DAILY') {
      // Advance by interval days until > today
      const candidate = new Date(today);
      candidate.setDate(candidate.getDate() + interval);
      if (countMax != null && count >= countMax) return null;
      if (until) {
        const y = parseInt(until.slice(0, 4), 10);
        const m = parseInt(until.slice(4, 6), 10) - 1;
        const d = parseInt(until.slice(6, 8), 10);
        if (candidate > new Date(y, m, d)) return null;
      }
      return toISODate(candidate);
    }

    if (freq === 'WEEKLY') {
      const byday = parts['BYDAY'];
      const targetDays = byday
        ? byday.split(',').map((d) => DAY_MAP[d.trim().toUpperCase()]).filter((d) => d != null)
        : [];
      if (targetDays.length === 0) return null;

      // Scan forward day by day (max 1 year)
      for (let offset = 1; offset <= 366; offset++) {
        const candidate = new Date(today);
        candidate.setDate(today.getDate() + offset);
        if (targetDays.includes(candidate.getDay())) {
          // Ensure it falls on the right week interval (relative to today's week start)
          const weeksSince = Math.floor(offset / 7);
          if (weeksSince % interval !== 0 && weeksSince > 0) continue;
          if (until) {
            const y = parseInt(until.slice(0, 4), 10);
            const m = parseInt(until.slice(4, 6), 10) - 1;
            const d = parseInt(until.slice(6, 8), 10);
            if (candidate > new Date(y, m, d)) return null;
          }
          count++;
          if (countMax != null && count > countMax) return null;
          return toISODate(candidate);
        }
      }
      return null;
    }

    if (freq === 'MONTHLY') {
      const bymonthday = parts['BYMONTHDAY'];
      const targetDays = bymonthday
        ? bymonthday.split(',').map((d) => parseInt(d.trim(), 10)).filter((d) => !isNaN(d))
        : [];
      if (targetDays.length === 0) return null;

      // Scan forward month by month (max 24 months)
      for (let monthOffset = 0; monthOffset <= 24; monthOffset += interval) {
        const baseDate = new Date(today.getFullYear(), today.getMonth() + monthOffset, 1);
        const daysInMonth = new Date(baseDate.getFullYear(), baseDate.getMonth() + 1, 0).getDate();

        for (const day of targetDays.sort((a, b) => a - b)) {
          if (day < 1 || day > daysInMonth) continue;
          const candidate = new Date(baseDate.getFullYear(), baseDate.getMonth(), day);
          if (candidate <= today) continue;
          if (until) {
            const y = parseInt(until.slice(0, 4), 10);
            const m = parseInt(until.slice(4, 6), 10) - 1;
            const d = parseInt(until.slice(6, 8), 10);
            if (candidate > new Date(y, m, d)) return null;
          }
          count++;
          if (countMax != null && count > countMax) return null;
          return toISODate(candidate);
        }
      }
      return null;
    }

    // Unsupported FREQ
    logger.warn('computeNextOccurrence: unsupported FREQ in RRULE', { recurrenceRule, freq });
    return null;
  } catch (err) {
    logger.warn('computeNextOccurrence: failed to parse RRULE', { recurrenceRule, err });
    return null;
  }
}

function toISODate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

// ---------------------------------------------------------------------------
// Functions
// ---------------------------------------------------------------------------

export async function listRouteTemplates(orgId: string, filters: ListRouteTemplatesFilters = {}) {
  const { clientId, contractId, active = true, search, page = 1, pageSize = 50 } = filters;
  const skip = (page - 1) * pageSize;

  const where = {
    orgId,
    active,
    ...(clientId ? { clientId } : {}),
    ...(contractId ? { contractId } : {}),
    ...(search ? { templateName: { contains: search, mode: 'insensitive' as const } } : {}),
  };

  const tenantPrisma = await getTenantPrisma();
  const [rawItems, total] = await Promise.all([
    tenantPrisma.routeTemplate.findMany({
      where,
      skip,
      take: pageSize,
      orderBy: { createdAt: 'desc' },
      include: {
        _count: { select: { stops: true } },
      },
    }),
    tenantPrisma.routeTemplate.count({ where }),
  ]);

  // Attach nextDispatchDate using recurrenceRule
  const items = rawItems.map((t) => ({
    ...t,
    nextDispatchDate: t.recurrenceRule
      ? computeNextOccurrence(t.recurrenceRule, t.recurrenceTimezone ?? 'America/Chicago')
      : null,
  }));

  return { items, total };
}

export async function getRouteTemplate(orgId: string, id: string) {
  const tenantPrisma = await getTenantPrisma();
  return tenantPrisma.routeTemplate.findFirst({
    where: { id, orgId },
    include: {
      stops: {
        orderBy: { sequenceOrder: 'asc' },
        include: {
          facility: {
            select: { id: true, name: true, city: true, state: true },
          },
        },
      },
    },
  });
}

export async function createRouteTemplate(orgId: string, data: RouteTemplateCreateInput) {
  const tenantPrisma = await getTenantPrisma();
  // Verify clientId belongs to this org
  const client = await tenantPrisma.carrierClient.findFirst({
    where: { id: data.clientId, orgId },
    select: { id: true },
  });
  if (!client) {
    throw new Error('Invalid client — does not belong to this organization');
  }

  // Verify contractId if supplied
  if (data.contractId) {
    const contract = await tenantPrisma.carrierContract.findFirst({
      where: { id: data.contractId, orgId },
      select: { id: true },
    });
    if (!contract) {
      throw new Error('Invalid contract — does not belong to this organization');
    }
  }

  // Verify defaultDriverId if supplied
  if (data.defaultDriverId) {
    const driver = await tenantPrisma.carrierDriver.findFirst({
      where: { id: data.defaultDriverId, orgId },
      select: { id: true },
    });
    if (!driver) {
      throw new Error('Invalid driver — does not belong to this organization');
    }
  }

  // Verify defaultTruckId if supplied
  if (data.defaultTruckId) {
    const truck = await tenantPrisma.carrierTruck.findFirst({
      where: { id: data.defaultTruckId, orgId },
      select: { id: true },
    });
    if (!truck) {
      throw new Error('Invalid truck — does not belong to this organization');
    }
  }

  return tenantPrisma.routeTemplate.create({
    data: {
      ...data,
      orgId,
    },
  });
}

export async function updateRouteTemplate(
  orgId: string,
  id: string,
  data: RouteTemplateUpdateInput
) {
  const tenantPrisma = await getTenantPrisma();
  const existing = await tenantPrisma.routeTemplate.findFirst({ where: { id, orgId } });
  if (!existing) return null;

  // IMPORTANT: Editing this template does NOT modify already-generated dispatches —
  // only future generations are affected.
  return tenantPrisma.routeTemplate.update({
    where: { id },
    data,
  });
}

export async function softDeleteRouteTemplate(orgId: string, id: string) {
  const tenantPrisma = await getTenantPrisma();
  const existing = await tenantPrisma.routeTemplate.findFirst({ where: { id, orgId } });
  if (!existing) return null;

  return tenantPrisma.routeTemplate.update({
    where: { id },
    data: { active: false },
  });
}
