import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getSession } from '@/lib/auth/supabase';
import { logger } from '@/lib/logger';
import { listRouteTemplates, createRouteTemplate } from '@/lib/carrier/route-templates';

const RouteTemplateCreateSchema = z.object({
  templateName: z.string().min(1),
  clientId: z.string().uuid(),
  contractId: z.string().uuid().optional(),
  scheduleType: z.string().min(1),
  recurrenceRule: z.string().optional(),
  recurrenceTimezone: z.string().optional(),
  scheduledDepartureTime: z.string().optional(),
  equipmentType: z.string().min(1),
  tempMinF: z.number().int().optional(),
  tempMaxF: z.number().int().optional(),
  maxWeightLbs: z.number().int().optional(),
  commodityDescription: z.string().optional(),
  estimatedMiles: z.number().int().optional(),
  defaultDriverId: z.string().uuid().optional(),
  defaultTruckId: z.string().uuid().optional(),
  autoGenerateDaysAhead: z.number().int().min(1).optional(),
  notes: z.string().optional(),
});

export async function GET(req: NextRequest) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const orgId = session.tenantId;
  if (!orgId) return NextResponse.json({ error: 'No organization' }, { status: 403 });

  try {
    const { searchParams } = req.nextUrl;
    const clientId = searchParams.get('client_id') ?? undefined;
    const contractId = searchParams.get('contract_id') ?? undefined;
    const search = searchParams.get('search') ?? undefined;
    const page = parseInt(searchParams.get('page') ?? '1', 10);
    const pageSize = parseInt(searchParams.get('pageSize') ?? '50', 10);

    const activeRaw = searchParams.get('active');
    const active = activeRaw === 'false' ? false : activeRaw === 'true' ? true : true;

    const result = await listRouteTemplates(orgId, { clientId, contractId, active, search, page, pageSize });

    return NextResponse.json({ data: { ...result, page, pageSize } });
  } catch (err) {
    logger.error('GET /api/v1/carrier/route-templates failed', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const orgId = session.tenantId;
  if (!orgId) return NextResponse.json({ error: 'No organization' }, { status: 403 });

  try {
    const body = await req.json();
    const parsed = RouteTemplateCreateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0].message },
        { status: 400 }
      );
    }

    const template = await createRouteTemplate(orgId, parsed.data);
    return NextResponse.json({ data: template }, { status: 201 });
  } catch (err) {
    logger.error('POST /api/v1/carrier/route-templates failed', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
