import { notFound, redirect } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { getSession } from '@/lib/auth/supabase';
import { getRouteTemplate } from '@/lib/carrier/route-templates';
import { RouteTemplateForm, type RouteTemplateFormData } from '@/components/carrier/templates/RouteTemplateForm';
import { DispatchPreview } from '@/components/carrier/templates/DispatchPreview';
import { TemplateStatusToggle } from './TemplateStatusToggle';
import type { StopBuilderStop } from '@/components/carrier/stops/StopCard';
import { AuditTrailFooter } from '@/components/audit-trail-footer';
import { prisma } from '@/lib/db/prisma';
import { TemplateEditMobile } from './TemplateEditMobile';

interface Props {
  params: Promise<{ id: string }>;
}

export default async function EditRouteTemplatePage({ params }: Props) {
  const session = await getSession();
  if (!session) redirect('/login');

  const { id } = await params;
  const [template, templateAudit] = await Promise.all([
    getRouteTemplate(session.tenantId, id),
    prisma.routeTemplate.findUnique({
      where: { id },
      select: {
        createdBy: { select: { firstName: true, lastName: true, email: true } },
        updatedBy: { select: { firstName: true, lastName: true, email: true } },
        createdAt: true,
        updatedAt: true,
      },
    }).catch(() => null),
  ]);

  if (!template) notFound();

  // Fetched server-side so the mobile selects render with the right option on the
  // first paint. Client-fetching them made the Client field flash "Select client…"
  // (a native select with no matching option falls back to its first one).
  const orgId = session.tenantId;
  const [clients, drivers, trucks, contracts, facilities] = await Promise.all([
    prisma.carrierClient.findMany({
      where: { orgId },
      select: { id: true, name: true },
      orderBy: { name: 'asc' },
    }),
    prisma.carrierDriver.findMany({
      where: { orgId, status: 'active' },
      select: { id: true, firstName: true, lastName: true },
      orderBy: { lastName: 'asc' },
    }),
    prisma.carrierTruck.findMany({
      where: { orgId, status: 'active' },
      select: { id: true, unitNumber: true },
      orderBy: { unitNumber: 'asc' },
    }),
    template.clientId
      ? prisma.carrierContract.findMany({
          where: { orgId, clientId: template.clientId },
          select: { id: true, contractNumber: true, contractName: true },
          orderBy: { contractNumber: 'asc' },
        })
      : Promise.resolve([]),
    prisma.carrierFacility.findMany({
      where: { orgId },
      select: { id: true, name: true, city: true, state: true },
      orderBy: { name: 'asc' },
    }),
  ]);

  // Map DB stops → StopBuilderStop format
  const stops: StopBuilderStop[] = template.stops.map((s) => ({
    id: s.id,
    facility_id: s.facilityId,
    facility_name: s.facility?.name ?? '',
    facility_city: s.facility?.city ?? null,
    facility_state: s.facility?.state ?? null,
    sequence_order: s.sequenceOrder,
    stop_type: s.stopType as StopBuilderStop['stop_type'],
    contact_name: s.contactName ?? null,
    contact_phone: s.contactPhone ?? null,
    expected_dwell_minutes: s.expectedDwellMinutes ?? null,
    commodity_description: s.commodityDescription ?? null,
    bol_required: s.bolRequired,
    pod_required: s.podRequired,
    special_instructions: s.specialInstructions ?? null,
    appt_window_start_offset_min: s.apptWindowStartOffsetMin ?? null,
    appt_window_end_offset_min: s.apptWindowEndOffsetMin ?? null,
    appointment_start: null,
    appointment_end: null,
  }));

  const formData: RouteTemplateFormData = {
    id: template.id,
    templateName: template.templateName,
    clientId: template.clientId,
    contractId: template.contractId ?? null,
    scheduleType: template.scheduleType,
    recurrenceRule: template.recurrenceRule ?? null,
    recurrenceTimezone: template.recurrenceTimezone,
    scheduledDepartureTime: template.scheduledDepartureTime ?? null,
    equipmentType: template.equipmentType,
    tempMinF: template.tempMinF ?? null,
    tempMaxF: template.tempMaxF ?? null,
    maxWeightLbs: template.maxWeightLbs ?? null,
    commodityDescription: template.commodityDescription ?? null,
    defaultDriverId: template.defaultDriverId ?? null,
    defaultTruckId: template.defaultTruckId ?? null,
    autoGenerateDaysAhead: template.autoGenerateDaysAhead,
    notes: template.notes ?? null,
    stops,
  };

  return (
    <>
      {/* Mobile-web design system — rendered below lg; desktop keeps its own layout */}
      <div className="lg:hidden -m-4">
        <TemplateEditMobile
          initialData={formData}
          templateId={id}
          initialActive={template.active}
          clients={clients}
          drivers={drivers}
          trucks={trucks}
          facilities={facilities}
          initialContracts={contracts}
        />
      </div>

      {/* Desktop */}
      <div className="hidden lg:block space-y-6">
      <div>
        <Link
          href="/carrier/templates"
          className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Route Templates
        </Link>
        <h1 className="mt-3 text-2xl sm:text-3xl font-bold tracking-tight text-foreground">
          Edit Route Template
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">{template.templateName}</p>
        <div className="mt-3">
          <TemplateStatusToggle templateId={id} initialActive={template.active} />
        </div>
      </div>

      <div className="rounded-lg border border-border bg-card p-6">
        <RouteTemplateForm initialData={formData} templateId={id} />
      </div>

      <div className="rounded-lg border border-border bg-card p-6">
        <DispatchPreview templateId={id} />
      </div>

      {templateAudit && (
        <AuditTrailFooter
          createdAt={templateAudit.createdAt}
          createdByName={templateAudit.createdBy ? `${templateAudit.createdBy.firstName ?? ''} ${templateAudit.createdBy.lastName ?? ''}`.trim() || null : null}
          createdByEmail={templateAudit.createdBy?.email ?? null}
          updatedAt={templateAudit.updatedAt}
          updatedByName={templateAudit.updatedBy ? `${templateAudit.updatedBy.firstName ?? ''} ${templateAudit.updatedBy.lastName ?? ''}`.trim() || null : null}
          updatedByEmail={templateAudit.updatedBy?.email ?? null}
        />
      )}
      </div>
    </>
  );
}
