/**
 * Nightly cron job: auto-generate carrier dispatches from active route templates.
 *
 * Schedule: Daily at 00:00 UTC
 * Authentication: CRON_SECRET bearer token
 *
 * Processing flow:
 * 1. Verify CRON_SECRET
 * 2. Fetch all active tenants that have at least one active route template
 * 3. For each tenant (in isolation — one failure does NOT block others):
 *    - Fetch active route templates with autoGenerateDaysAhead > 0
 *    - For each template: compute generateThroughDate and call generateDispatches
 *    - Fire after() notifications for each generated dispatch
 * 4. Return summary
 */

import { after } from 'next/server';
import { NextRequest, NextResponse } from 'next/server';
import { getAdminDb } from '@/lib/db/admin-prisma';
import { getTenantPrismaForOrg } from '@/lib/context/tenant-context';
import { generateDispatches } from '@/lib/carrier/dispatch-generator';
import { createNotification } from '@/lib/carrier/in-app-notifications';
import { logger } from '@/lib/logger';
import { CronFailures, cronStatus } from '@/lib/cron/failure-report';
import { verifyCronSecret, cronUnauthorizedResponse } from '@/lib/security/cron-auth';

export const dynamic = 'force-dynamic';

function toISODate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

export async function GET(request: NextRequest) {
  logger.info('[CRON] carrier-auto-dispatch: Starting nightly dispatch generation');

  // 1. Verify CRON_SECRET (timing-safe comparison)
  if (!verifyCronSecret(request)) {
    logger.error('[CRON] carrier-auto-dispatch: Unauthorized request');
    return cronUnauthorizedResponse();
  }

  /**
   * quick-606 — ROUTE. This carried an "@bypass_rls reason: system-operation"
   * comment and NOTHING in this file ever set app.bypass_rls, so the comment
   * was decorative in the way the digests' "DECORATIVE" note was.
   *
   * quick-604 attributed this route's 500 to fixture data ("Template has no
   * recurrenceRule"). quick-606 re-measured it and never reached that code: it
   * raised TC001 right here, on the tenant sweep. Both readings are honest
   * measurements of the same source — what differed is what an EARLIER request
   * left on the max:1 pool (unmigrated-path-tripwire.md §8 item 7). Genuinely
   * cross-tenant: the sweep IS the list.
   * SAFETY: gated by the CRON_SECRET check above.
   */
  let tenants: Array<{ id: string; name: string }>;
  try {
    const adminDb = await getAdminDb('auto-dispatch generation tenant sweep');
    /**
     * quick-606 — THE NESTED `routeTemplates: { some: { active: true } }` FILTER
     * IS GONE, and this is the second of two grants the path needed that no
     * static read of the source predicted (`admin-connection.md` §5).
     *
     * That filter compiles to a read of `route_templates`, on which `app_admin`
     * has NO GRANT — measured, `42501 permission denied for table
     * route_templates`, on the first run after this sweep was routed.
     *
     * Two ways to close it, and the cheaper one was chosen deliberately:
     *   (a) `GRANT SELECT ON route_templates TO app_admin` — a second table on a
     *       connection that BYPASSES RLS entirely, for what is only an
     *       optimisation;
     *   (b) drop the filter and let the per-tenant query, which already runs
     *       under a tenant-scoped client, find nothing.
     * (b) widens nothing. The cost is one extra `route_templates` query per
     *     template-less tenant, and `orgs_processed` keeps its old meaning
     *     because the loop below `continue`s before counting when a tenant has
     *     no templates.
     */
    tenants = await adminDb.tenant.findMany({
      where: { isActive: true },
      select: { id: true, name: true },
    });

    logger.info(`[CRON] carrier-auto-dispatch: Found ${tenants.length} active tenant(s)`);
  } catch (error) {
    logger.error('[CRON] carrier-auto-dispatch: Failed to fetch tenants', error);
    return NextResponse.json({ success: false, error: 'Failed to fetch tenants' }, { status: 500 });
  }

  // 3. Initialize summary
  const summary = {
    orgs_processed: 0,
    total_dispatches_created: 0,
    total_loads_created: 0,
    total_stops_created: 0,
    total_errors: 0,
    details: [] as Array<{
      orgId: string;
      orgName: string;
      dispatches_created: number;
      loads_created: number;
      stops_created: number;
      errors: number;
    }>,
  };
  const failures = new CronFailures();

  // 4. Process each tenant in isolation
  for (const tenant of tenants) {
    let tenantDispatchesCreated = 0;
    let tenantLoadsCreated = 0;
    let tenantStopsCreated = 0;
    let tenantErrors = 0;

    try {
      // Fetch active route templates with autoGenerateDaysAhead > 0
      // quick-606 — per-tenant work belongs on a client that SETS the GUC, not
      // on the bare one. `orgId` stays in the where clause: RouteTemplate is in
      // withTenantRLS's EXEMPT_MODELS (it carries orgId, not tenantId), so the
      // Prisma layer injects nothing here and the explicit filter is the only
      // application-layer scope there is.
      const tenantDb = await getTenantPrismaForOrg(tenant.id);
      const templates = await tenantDb.routeTemplate.findMany({
        where: {
          orgId: tenant.id,
          active: true,
          autoGenerateDaysAhead: { gt: 0 },
        },
      });

      if (templates.length === 0) {
        // quick-606 — the tenant list is no longer pre-filtered on
        // `routeTemplates: { some: … }` (see above), so a template-less tenant
        // now reaches this loop. `continue` BEFORE `orgs_processed++` so the
        // reported number keeps the meaning it had when the filter did this job.
        continue;
      }

      logger.info(`[CRON] carrier-auto-dispatch: Processing tenant ${tenant.name} (${tenant.id}) — ${templates.length} template(s)`);

      for (const template of templates) {
        try {
          // Compute generateThroughDate as today + autoGenerateDaysAhead
          const throughDate = new Date();
          throughDate.setDate(throughDate.getDate() + template.autoGenerateDaysAhead);
          const generateThroughDate = toISODate(throughDate);

          const result = await generateDispatches(tenant.id, template.id, generateThroughDate);
          tenantDispatchesCreated += result.dispatchesCreated;
          tenantLoadsCreated += result.loadsCreated;
          tenantStopsCreated += result.stopsCreated;

          if (result.errors.length > 0) {
            tenantErrors += result.errors.length;
            /**
             * `generateDispatches` returns its per-day errors as `string[]`.
             * They were counted into `total_errors` and then sat beside an
             * unconditional `success: true`, and were only ever `logger.warn`ed
             * — so a generation failure never reached Sentry as an exception.
             * Naming each one here replaces that single summary warn.
             */
            for (const genErr of result.errors) {
              failures.record(
                `[CRON] carrier-auto-dispatch: Template ${template.id} generation error`,
                `template:${template.id}`,
                genErr,
                { tenantId: tenant.id, tenantName: tenant.name },
              );
            }
          }

          logger.info(`[CRON] carrier-auto-dispatch: Template ${template.id} created ${result.dispatchesCreated} dispatch(es), ${result.loadsCreated} load(s), ${result.stopsCreated} stop(s), skipped ${result.skippedExisting}`);

          // Fire after() notifications for each generated dispatch
          for (const notif of result.notifications) {
            const { orgId, dispatchId, templateName, dispatchNumber, needsAssignment } = notif;
            if (needsAssignment) {
              after(() =>
                createNotification({
                  orgId,
                  userId: null,
                  type: 'needs_assignment',
                  title: 'Dispatch Needs Assignment',
                  message: `Auto-generated dispatch ${dispatchNumber} from template "${templateName}" needs driver/truck assignment`,
                  entityType: 'dispatch',
                  entityId: dispatchId,
                })
              );
            } else {
              after(() =>
                createNotification({
                  orgId,
                  userId: null,
                  type: 'dispatch_generated',
                  title: 'Dispatch Generated',
                  message: `Dispatch ${dispatchNumber} auto-generated from template "${templateName}"`,
                  entityType: 'dispatch',
                  entityId: dispatchId,
                })
              );
            }
          }
        } catch (templateErr) {
          // The loop still continues — one bad template must not stop the rest.
          tenantErrors++;
          failures.record(
            `[CRON] carrier-auto-dispatch: Error processing template ${template.id} for tenant ${tenant.name}`,
            `template:${template.id}`,
            templateErr,
            { tenantId: tenant.id, tenantName: tenant.name },
          );
        }
      }

      summary.orgs_processed++;
      summary.total_dispatches_created += tenantDispatchesCreated;
      summary.total_loads_created += tenantLoadsCreated;
      summary.total_stops_created += tenantStopsCreated;
      summary.total_errors += tenantErrors;
      summary.details.push({
        orgId: tenant.id,
        orgName: tenant.name,
        dispatches_created: tenantDispatchesCreated,
        loads_created: tenantLoadsCreated,
        stops_created: tenantStopsCreated,
        errors: tenantErrors,
      });
    } catch (tenantErr) {
      // One tenant failure must NOT block others
      failures.record(
        `[CRON] carrier-auto-dispatch: Failed to process tenant ${tenant.name} (${tenant.id})`,
        `tenant:${tenant.id}`,
        tenantErr,
        { tenantName: tenant.name },
      );
      summary.total_errors++;
      summary.details.push({
        orgId: tenant.id,
        orgName: tenant.name,
        dispatches_created: 0,
        loads_created: 0,
        stops_created: 0,
        errors: 1,
      });
    }
  }

  const report = failures.report();
  logger.info('[CRON] carrier-auto-dispatch: Completed', { ...summary, ...report });
  return NextResponse.json(
    { success: failures.ok, ...summary, ...report },
    { status: cronStatus(failures) },
  );
}
