/**
 * Nightly cron job: auto-generate carrier dispatches from active route templates.
 *
 * Schedule: Daily at 00:00 UTC
 * Authentication: CRON_SECRET bearer token
 *
 * Processing flow:
 * 1. Verify CRON_SECRET
 * 2. Fetch all active tenants that have at least one active route template
 * 3. For each tenant (in isolation — one failure does NOT block others):
 *    - Fetch active route templates with autoGenerateDaysAhead > 0
 *    - For each template: compute generateThroughDate and call generateDispatches
 *    - Fire after() notifications for each generated dispatch
 * 4. Return summary
 */

import { after } from 'next/server';
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import { generateDispatches } from '@/lib/carrier/dispatch-generator';
import { createNotification } from '@/lib/carrier/in-app-notifications';
import { logger } from '@/lib/logger';

export const dynamic = 'force-dynamic';

function toISODate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

export async function GET(request: NextRequest) {
  logger.info('[CRON] carrier-auto-dispatch: Starting nightly dispatch generation');

  // 1. Verify CRON_SECRET
  const authHeader = request.headers.get('authorization');
  const expectedAuth = `Bearer ${process.env.CRON_SECRET}`;

  if (authHeader !== expectedAuth) {
    logger.error('[CRON] carrier-auto-dispatch: Unauthorized request');
    return new Response('Unauthorized', { status: 401 });
  }

  /**
   * @bypass_rls reason: system-operation
   * WHY: This cron job runs cross-tenant to generate dispatches for ALL active tenants.
   *      It has no user context to scope RLS policies to a single tenant.
   * SAFETY: Gated by CRON_SECRET header check above — only callable by Vercel Cron.
   */
  let tenants: Array<{ id: string; name: string }>;
  try {
    tenants = await prisma.tenant.findMany({
      where: {
        isActive: true,
        routeTemplates: { some: { active: true } },
      },
      select: { id: true, name: true },
    });

    logger.info(`[CRON] carrier-auto-dispatch: Found ${tenants.length} active tenant(s) with route templates`);
  } catch (error) {
    logger.error('[CRON] carrier-auto-dispatch: Failed to fetch tenants', error);
    return NextResponse.json({ success: false, error: 'Failed to fetch tenants' }, { status: 500 });
  }

  // 3. Initialize summary
  const summary = {
    orgs_processed: 0,
    total_dispatches_created: 0,
    total_loads_created: 0,
    total_stops_created: 0,
    total_errors: 0,
    details: [] as Array<{
      orgId: string;
      orgName: string;
      dispatches_created: number;
      loads_created: number;
      stops_created: number;
      errors: number;
    }>,
  };

  // 4. Process each tenant in isolation
  for (const tenant of tenants) {
    let tenantDispatchesCreated = 0;
    let tenantLoadsCreated = 0;
    let tenantStopsCreated = 0;
    let tenantErrors = 0;

    try {
      // Fetch active route templates with autoGenerateDaysAhead > 0
      const templates = await prisma.routeTemplate.findMany({
        where: {
          orgId: tenant.id,
          active: true,
          autoGenerateDaysAhead: { gt: 0 },
        },
      });

      logger.info(`[CRON] carrier-auto-dispatch: Processing tenant ${tenant.name} (${tenant.id}) — ${templates.length} template(s)`);

      for (const template of templates) {
        try {
          // Compute generateThroughDate as today + autoGenerateDaysAhead
          const throughDate = new Date();
          throughDate.setDate(throughDate.getDate() + template.autoGenerateDaysAhead);
          const generateThroughDate = toISODate(throughDate);

          const result = await generateDispatches(tenant.id, template.id, generateThroughDate);
          tenantDispatchesCreated += result.dispatchesCreated;
          tenantLoadsCreated += result.loadsCreated;
          tenantStopsCreated += result.stopsCreated;

          if (result.errors.length > 0) {
            tenantErrors += result.errors.length;
            logger.warn(`[CRON] carrier-auto-dispatch: Template ${template.id} had ${result.errors.length} error(s)`, {
              errors: result.errors,
            });
          }

          logger.info(`[CRON] carrier-auto-dispatch: Template ${template.id} created ${result.dispatchesCreated} dispatch(es), ${result.loadsCreated} load(s), ${result.stopsCreated} stop(s), skipped ${result.skippedExisting}`);

          // Fire after() notifications for each generated dispatch
          for (const notif of result.notifications) {
            const { orgId, dispatchId, templateName, dispatchNumber, needsAssignment } = notif;
            if (needsAssignment) {
              after(() =>
                createNotification({
                  orgId,
                  userId: null,
                  type: 'needs_assignment',
                  title: 'Dispatch Needs Assignment',
                  message: `Auto-generated dispatch ${dispatchNumber} from template "${templateName}" needs driver/truck assignment`,
                  entityType: 'dispatch',
                  entityId: dispatchId,
                })
              );
            } else {
              after(() =>
                createNotification({
                  orgId,
                  userId: null,
                  type: 'dispatch_generated',
                  title: 'Dispatch Generated',
                  message: `Dispatch ${dispatchNumber} auto-generated from template "${templateName}"`,
                  entityType: 'dispatch',
                  entityId: dispatchId,
                })
              );
            }
          }
        } catch (templateErr) {
          tenantErrors++;
          logger.error(`[CRON] carrier-auto-dispatch: Error processing template ${template.id} for tenant ${tenant.name}`, templateErr);
        }
      }

      summary.orgs_processed++;
      summary.total_dispatches_created += tenantDispatchesCreated;
      summary.total_loads_created += tenantLoadsCreated;
      summary.total_stops_created += tenantStopsCreated;
      summary.total_errors += tenantErrors;
      summary.details.push({
        orgId: tenant.id,
        orgName: tenant.name,
        dispatches_created: tenantDispatchesCreated,
        loads_created: tenantLoadsCreated,
        stops_created: tenantStopsCreated,
        errors: tenantErrors,
      });
    } catch (tenantErr) {
      // One tenant failure must NOT block others
      logger.error(`[CRON] carrier-auto-dispatch: Failed to process tenant ${tenant.name} (${tenant.id})`, tenantErr);
      summary.total_errors++;
      summary.details.push({
        orgId: tenant.id,
        orgName: tenant.name,
        dispatches_created: 0,
        loads_created: 0,
        stops_created: 0,
        errors: 1,
      });
    }
  }

  logger.info('[CRON] carrier-auto-dispatch: Completed', summary);
  return NextResponse.json({ success: true, ...summary });
}
