import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getSession } from '@/lib/auth/supabase';
import { logger } from '@/lib/logger';
import { getRouteTemplate, updateRouteTemplate, softDeleteRouteTemplate } from '@/lib/carrier/route-templates';

const RouteTemplateUpdateSchema = z.object({
  templateName: z.string().min(1).optional(),
  clientId: z.string().uuid().optional(),
  contractId: z.string().uuid().optional(),
  scheduleType: z.string().optional(),
  recurrenceRule: z.string().optional(),
  recurrenceTimezone: z.string().optional(),
  scheduledDepartureTime: z.string().optional(),
  equipmentType: z.string().optional(),
  tempMinF: z.number().int().optional(),
  tempMaxF: z.number().int().optional(),
  maxWeightLbs: z.number().int().optional(),
  commodityDescription: z.string().optional(),
  estimatedMiles: z.number().int().optional(),
  defaultDriverId: z.string().uuid().optional(),
  defaultTruckId: z.string().uuid().optional(),
  autoGenerateDaysAhead: z.number().int().min(1).optional(),
  notes: z.string().optional(),
});

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const orgId = session.tenantId;
  if (!orgId) return NextResponse.json({ error: 'No organization' }, { status: 403 });

  try {
    const { id } = await params;
    const template = await getRouteTemplate(orgId, id);
    if (!template) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    return NextResponse.json({ data: template });
  } catch (err) {
    logger.error('GET /api/v1/carrier/route-templates/[id] failed', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PATCH(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const orgId = session.tenantId;
  if (!orgId) return NextResponse.json({ error: 'No organization' }, { status: 403 });

  try {
    const { id } = await params;
    const body = await req.json();
    const parsed = RouteTemplateUpdateSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0].message },
        { status: 400 }
      );
    }

    const template = await updateRouteTemplate(orgId, id, parsed.data);
    if (!template) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    return NextResponse.json({ data: template });
  } catch (err) {
    logger.error('PATCH /api/v1/carrier/route-templates/[id] failed', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const orgId = session.tenantId;
  if (!orgId) return NextResponse.json({ error: 'No organization' }, { status: 403 });

  try {
    const { id } = await params;
    const result = await softDeleteRouteTemplate(orgId, id);
    if (!result) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    return NextResponse.json({ data: { id: result.id, active: false } });
  } catch (err) {
    logger.error('DELETE /api/v1/carrier/route-templates/[id] failed', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
