'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import {
  MobileScreen,
  NavHeader,
  NavTextButton,
  SectionHeader,
  FieldGroup,
  PrimaryButton,
  type FieldDef,
} from '@/components/ui/ds';
import { saveRouteTemplate } from '@/actions/carrier/save-route-template';
import type { StopBuilderStop } from '@/components/carrier/stops/StopCard';
import { MobileStopsEditor, type FacilityOption } from '@/components/carrier/stops/MobileStopsEditor';

const EQUIPMENT_TYPES = [
  { label: 'Dry Van', value: 'dry_van' },
  { label: 'Flatbed', value: 'flatbed' },
  { label: 'Reefer', value: 'reefer' },
  { label: 'Tanker', value: 'tanker' },
  { label: 'Step Deck', value: 'step_deck' },
  { label: 'Other', value: 'other' },
];
const SCHEDULE_TYPES = [
  { label: 'Fixed days', value: 'fixed_days' },
  { label: 'Frequency', value: 'frequency' },
  { label: 'On call', value: 'on_call' },
];
const TIMEZONES = [
  { label: 'Eastern (ET)', value: 'America/New_York' },
  { label: 'Central (CT)', value: 'America/Chicago' },
  { label: 'Mountain (MT)', value: 'America/Denver' },
  { label: 'Pacific (PT)', value: 'America/Los_Angeles' },
  { label: 'Arizona (AZ)', value: 'America/Phoenix' },
  { label: 'Alaska (AKT)', value: 'America/Anchorage' },
  { label: 'Hawaii (HT)', value: 'Pacific/Honolulu' },
  { label: 'UTC', value: 'UTC' },
];
const FREQ_OPTIONS = [
  { label: 'Weekly', value: 'WEEKLY' },
  { label: 'Daily', value: 'DAILY' },
  { label: 'Monthly', value: 'MONTHLY' },
];
const WEEK_DAYS = [
  { key: 'MO', label: 'M' },
  { key: 'TU', label: 'T' },
  { key: 'WE', label: 'W' },
  { key: 'TH', label: 'T' },
  { key: 'FR', label: 'F' },
  { key: 'SA', label: 'S' },
  { key: 'SU', label: 'S' },
];

interface ClientItem { id: string; name: string }
interface ContractItem { id: string; contractNumber: string; contractName: string | null }
interface DriverItem { id: string; firstName: string; lastName: string }
interface TruckItem { id: string; unitNumber: string }

// ---------------------------------------------------------------------------
// New Route Template — mobile-web design system create page (carrier)
// ---------------------------------------------------------------------------

export function NewTemplateMobile({
  clients,
  drivers,
  trucks,
  facilities,
}: {
  clients: ClientItem[];
  drivers: DriverItem[];
  trucks: TruckItem[];
  facilities: FacilityOption[];
}) {
  const router = useRouter();

  const [templateName, setTemplateName] = useState('');
  const [clientId, setClientId] = useState('');
  const [contractId, setContractId] = useState('');
  const [contracts, setContracts] = useState<ContractItem[]>([]);
  const [scheduleType, setScheduleType] = useState('fixed_days');
  const [rruleFrequency, setRruleFrequency] = useState<'DAILY' | 'WEEKLY' | 'MONTHLY'>('WEEKLY');
  const [rruleSelectedDays, setRruleSelectedDays] = useState<string[]>([]);
  const [rruleMonthlyDays, setRruleMonthlyDays] = useState('');
  const [recurrenceTimezone, setRecurrenceTimezone] = useState('America/Chicago');
  const [scheduledDepartureTime, setScheduledDepartureTime] = useState('');
  const [equipmentType, setEquipmentType] = useState('dry_van');
  const [tempMinF, setTempMinF] = useState('');
  const [tempMaxF, setTempMaxF] = useState('');
  const [maxWeightLbs, setMaxWeightLbs] = useState('');
  const [commodityDescription, setCommodityDescription] = useState('');
  const [defaultDriverId, setDefaultDriverId] = useState('');
  const [defaultTruckId, setDefaultTruckId] = useState('');
  const [autoGenerateDaysAhead, setAutoGenerateDaysAhead] = useState('7');
  const [notes, setNotes] = useState('');
  const [stops, setStops] = useState<StopBuilderStop[]>([]);

  const [saving, setSaving] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const showRecurrence = scheduleType === 'fixed_days' || scheduleType === 'frequency';

  const recurrenceRule = useMemo(() => {
    if (!showRecurrence) return '';
    if (rruleFrequency === 'DAILY') return 'FREQ=DAILY';
    if (rruleFrequency === 'WEEKLY') {
      return rruleSelectedDays.length === 0 ? 'FREQ=WEEKLY' : `FREQ=WEEKLY;BYDAY=${rruleSelectedDays.join(',')}`;
    }
    return rruleMonthlyDays.trim() ? `FREQ=MONTHLY;BYMONTHDAY=${rruleMonthlyDays.trim()}` : 'FREQ=MONTHLY';
  }, [showRecurrence, rruleFrequency, rruleSelectedDays, rruleMonthlyDays]);

  useEffect(() => {
    if (!clientId) {
      setContracts([]);
      return;
    }
    let cancelled = false;
    fetch(`/api/v1/carrier/contracts?client_id=${clientId}&pageSize=100`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        if (!cancelled) setContracts((d?.data?.items ?? []) as ContractItem[]);
      })
      .catch(() => {
        if (!cancelled) setContracts([]);
      });
    return () => {
      cancelled = true;
    };
  }, [clientId]);

  function validate(): boolean {
    const e: Record<string, string> = {};
    if (!templateName.trim()) e.templateName = 'Template name is required';
    if (!clientId) e.clientId = 'Client is required';
    if (!equipmentType) e.equipmentType = 'Equipment type is required';
    if (!scheduleType) e.scheduleType = 'Schedule type is required';
    // The server requires at least one stop — say so here rather than failing on save.
    if (stops.length === 0) e.stops = 'Add at least one stop';
    if (stops.some((s) => !s.facility_id)) e.stops = 'Every stop needs a facility';
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  async function save() {
    if (!validate()) {
      toast.error('Check the highlighted fields');
      return;
    }
    setSaving(true);
    try {
      const result = await saveRouteTemplate({
        templateName: templateName.trim(),
        clientId,
        contractId: contractId || undefined,
        scheduleType,
        recurrenceRule: recurrenceRule || undefined,
        recurrenceTimezone,
        scheduledDepartureTime: scheduledDepartureTime || undefined,
        equipmentType,
        tempMinF: tempMinF ? Number(tempMinF) : undefined,
        tempMaxF: tempMaxF ? Number(tempMaxF) : undefined,
        maxWeightLbs: maxWeightLbs ? Number(maxWeightLbs) : undefined,
        commodityDescription: commodityDescription || undefined,
        defaultDriverId: defaultDriverId || undefined,
        defaultTruckId: defaultTruckId || undefined,
        autoGenerateDaysAhead: autoGenerateDaysAhead ? Number(autoGenerateDaysAhead) : undefined,
        notes: notes || undefined,
        stops,
      });
      if (!result.success) {
        toast.error(result.error ?? 'Failed to create template');
        setSaving(false);
        return;
      }
      navigator.vibrate?.(10);
      toast.success('Template created');
      router.push('/carrier/templates');
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Something went wrong');
      setSaving(false);
    }
  }

  const detailFields: FieldDef[] = [
    {
      key: 'templateName',
      label: 'Name *',
      input: {
        value: templateName,
        onChange: (v) => {
          setTemplateName(v);
          if (errors.templateName) setErrors((e) => ({ ...e, templateName: '' }));
        },
        placeholder: 'e.g. Chicago to Dallas',
        error: errors.templateName || undefined,
      },
    },
    {
      key: 'clientId',
      label: 'Client *',
      input: {
        value: clientId,
        onChange: (v) => {
          setClientId(v);
          setContractId('');
          if (errors.clientId) setErrors((e) => ({ ...e, clientId: '' }));
        },
        options: [{ label: 'Select client…', value: '' }, ...clients.map((c) => ({ label: c.name, value: c.id }))],
        error: errors.clientId || undefined,
      },
    },
    ...(contracts.length > 0
      ? [
          {
            key: 'contractId',
            label: 'Contract',
            input: {
              value: contractId,
              onChange: setContractId,
              options: [
                { label: 'None', value: '' },
                ...contracts.map((c) => ({ label: c.contractName ?? c.contractNumber, value: c.id })),
              ],
            },
          } as FieldDef,
        ]
      : []),
  ];

  const scheduleFields: FieldDef[] = [
    { key: 'scheduleType', label: 'Schedule', input: { value: scheduleType, onChange: setScheduleType, options: SCHEDULE_TYPES } },
    ...(showRecurrence
      ? ([
          { key: 'frequency', label: 'Repeats', input: { value: rruleFrequency, onChange: (v: string) => setRruleFrequency(v as 'DAILY' | 'WEEKLY' | 'MONTHLY'), options: FREQ_OPTIONS } },
          ...(rruleFrequency === 'MONTHLY'
            ? [{ key: 'monthlyDays', label: 'Days of month', input: { value: rruleMonthlyDays, onChange: (v: string) => setRruleMonthlyDays(v.replace(/[^\d,]/g, '')), inputMode: 'numeric' as const, placeholder: 'e.g. 1,15' } }]
            : []),
          { key: 'departureTime', label: 'Departs at', input: { value: scheduledDepartureTime, onChange: setScheduledDepartureTime, type: 'time' } },
          { key: 'timezone', label: 'Timezone', input: { value: recurrenceTimezone, onChange: setRecurrenceTimezone, options: TIMEZONES } },
          { key: 'autoGen', label: 'Generate days ahead', input: { value: autoGenerateDaysAhead, onChange: (v: string) => setAutoGenerateDaysAhead(v.replace(/[^\d]/g, '')), inputMode: 'numeric' as const, placeholder: '7' } },
        ] as FieldDef[])
      : []),
  ];

  const equipmentFields: FieldDef[] = [
    { key: 'equipmentType', label: 'Equipment *', input: { value: equipmentType, onChange: setEquipmentType, options: EQUIPMENT_TYPES, error: errors.equipmentType || undefined } },
    ...(equipmentType === 'reefer'
      ? ([
          { key: 'tempMinF', label: 'Temp min (°F)', input: { value: tempMinF, onChange: (v: string) => setTempMinF(v.replace(/[^\d-]/g, '')), inputMode: 'numeric' as const, placeholder: '—' } },
          { key: 'tempMaxF', label: 'Temp max (°F)', input: { value: tempMaxF, onChange: (v: string) => setTempMaxF(v.replace(/[^\d-]/g, '')), inputMode: 'numeric' as const, placeholder: '—' } },
        ] as FieldDef[])
      : []),
    { key: 'maxWeightLbs', label: 'Max weight (lbs)', input: { value: maxWeightLbs, onChange: (v) => setMaxWeightLbs(v.replace(/[^\d]/g, '')), inputMode: 'numeric', placeholder: '—' } },
    { key: 'commodityDescription', label: 'Commodity', input: { value: commodityDescription, onChange: setCommodityDescription, placeholder: 'e.g. Dry goods' } },
  ];

  const defaultsFields: FieldDef[] = [
    { key: 'defaultDriverId', label: 'Default driver', input: { value: defaultDriverId, onChange: setDefaultDriverId, options: [{ label: 'None', value: '' }, ...drivers.map((d) => ({ label: `${d.firstName} ${d.lastName}`, value: d.id }))] } },
    { key: 'defaultTruckId', label: 'Default truck', input: { value: defaultTruckId, onChange: setDefaultTruckId, options: [{ label: 'None', value: '' }, ...trucks.map((t) => ({ label: `Unit ${t.unitNumber}`, value: t.id }))] } },
  ];

  const notesFields: FieldDef[] = [
    { key: 'notes', label: 'Notes', input: { value: notes, onChange: setNotes, multiline: true, placeholder: 'Anything worth remembering' } },
  ];

  const canSave = templateName.trim().length > 0 && clientId.length > 0 && stops.length > 0 && !saving;

  return (
    <MobileScreen className="pb-10 pt-2">
      <NavHeader
        title="New Template"
        left={<NavTextButton label="Cancel" onClick={() => router.push('/carrier/templates')} />}
        right={<NavTextButton label={saving ? 'Creating…' : 'Create'} emphasized onClick={save} disabled={!canSave} />}
      />

      <div className="pb-2 pt-1">
        <p className="text-center text-[13px] text-ds-txt3">
          A recurring route that generates trips automatically.
        </p>
      </div>

      <div className="space-y-6">
        <div>
          <SectionHeader title="Details" />
          <FieldGroup fields={detailFields} isEditing />
        </div>

        <div>
          <SectionHeader title="Schedule" />
          <FieldGroup fields={scheduleFields} isEditing />
          {showRecurrence && rruleFrequency === 'WEEKLY' ? (
            <div className="mt-2 rounded-[20px] bg-ds-card p-4">
              <p className="mb-2 text-[13px] text-ds-txt2">Repeat on</p>
              <div className="flex gap-2">
                {WEEK_DAYS.map((d, i) => {
                  const on = rruleSelectedDays.includes(d.key);
                  return (
                    <button
                      key={d.key}
                      type="button"
                      aria-pressed={on}
                      aria-label={['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][i]}
                      onClick={() =>
                        setRruleSelectedDays((prev) =>
                          prev.includes(d.key) ? prev.filter((x) => x !== d.key) : [...prev, d.key],
                        )
                      }
                      className={`h-10 flex-1 rounded-[10px] text-[13px] font-semibold transition active:opacity-75 ${
                        on ? 'bg-ds-accent text-white' : 'bg-ds-input text-ds-txt2'
                      }`}
                    >
                      {d.label}
                    </button>
                  );
                })}
              </div>
            </div>
          ) : null}
        </div>

        <div>
          <SectionHeader title="Equipment" />
          <FieldGroup fields={equipmentFields} isEditing />
        </div>

        <div>
          <SectionHeader title="Defaults" />
          <FieldGroup fields={defaultsFields} isEditing />
        </div>

        {/* Stops — required by the server, so they're part of create, not an afterthought */}
        <MobileStopsEditor stops={stops} onChange={setStops} facilities={facilities} error={errors.stops} mode="template" />

        <div>
          <SectionHeader title="Notes" />
          <FieldGroup fields={notesFields} isEditing />
        </div>

        <PrimaryButton label={saving ? 'Creating…' : 'Create Template'} onClick={save} disabled={!canSave} loading={saving} />
      </div>
    </MobileScreen>
  );
}
