/**
 * quick-603 — `carrier-auto-dispatch`.
 *
 * It already counted `total_errors` and already used the real logger arity. What
 * it did with them was return `success: true` and 200 anyway — and
 * `generateDispatches`' own `string[]` errors were only `logger.warn`ed, so a
 * generation failure never reached Sentry as an exception at all.
 */
import { describe, it, expect, vi, beforeEach } from 'vitest';
import {
  cronRequest,
  loggerDouble,
  InjectedFailure,
  expectNamedInLog,
  expectFailureReported,
} from './_cron-test-kit';

const h = vi.hoisted(() => ({
  tenantFindMany: vi.fn(),
  templateFindMany: vi.fn(),
  generateDispatches: vi.fn(),
  createNotification: vi.fn(),
}));

vi.mock('@/lib/logger', async (io) => loggerDouble(io));
vi.mock('next/server', async (io) => {
  const actual = (await io()) as Record<string, unknown>;
  // `after()` outside a request scope throws. The deferred notifications are not
  // what this test is about, so it is replaced with an immediate no-op.
  return { ...actual, after: vi.fn() };
});
vi.mock('@/lib/db/prisma', () => ({
  prisma: {
    tenant: { findMany: h.tenantFindMany },
    routeTemplate: { findMany: h.templateFindMany },
  },
}));
vi.mock('@/lib/carrier/dispatch-generator', () => ({ generateDispatches: h.generateDispatches }));
vi.mock('@/lib/carrier/in-app-notifications', () => ({ createNotification: h.createNotification }));

/** M = 4 templates on one tenant; template 2 of 4 throws. */
const M = 4;
const TEMPLATES = Array.from({ length: M }, (_, i) => ({
  id: `tpl-${i}`,
  autoGenerateDaysAhead: 7,
}));
const FAILING_TEMPLATE = 'tpl-1';
const injected = new InjectedFailure(FAILING_TEMPLATE);

const CLEAN_RESULT = {
  dispatchesCreated: 2,
  skippedExisting: 0,
  loadsCreated: 1,
  stopsCreated: 3,
  errors: [] as string[],
  notifications: [] as unknown[],
};

describe('cron/carrier-auto-dispatch — injection', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    h.tenantFindMany.mockResolvedValue([{ id: 'tenant-a', name: 'Alpha Freight' }]);
    h.templateFindMany.mockResolvedValue(TEMPLATES);
    h.generateDispatches.mockImplementation(async (_org: string, templateId: string) =>
      templateId === FAILING_TEMPLATE ? Promise.reject(injected) : CLEAN_RESULT,
    );
  });

  it('reports the failure, names the template, and STILL generates for the other M-1', async () => {
    const { logger } = await import('@/lib/logger');
    const { GET } = await import('@/app/api/cron/carrier-auto-dispatch/route');

    const res = await GET(cronRequest());
    const body = await res.json();

    // 1. THE RESPONSE SAYS SO.
    expectFailureReported(body, res.status, FAILING_TEMPLATE);

    // 2. THE LOG CARRIES A REAL MESSAGE.
    expectNamedInLog(logger.error as never, injected);

    // 3. THE BATCH STILL CONTINUED — M generation attempts, not 1 and not 2.
    expect(h.generateDispatches).toHaveBeenCalledTimes(M);
    expect(body.total_dispatches_created).toBe((M - 1) * CLEAN_RESULT.dispatchesCreated);
    expect(body.total_errors).toBe(1);
  });

  it("names generateDispatches' own string errors, which used to be logger.warn-only", async () => {
    h.generateDispatches.mockResolvedValue({
      ...CLEAN_RESULT,
      errors: ['no recurrenceRule', 'facility missing'],
    });

    const { GET } = await import('@/app/api/cron/carrier-auto-dispatch/route');
    const res = await GET(cronRequest());
    const body = await res.json();

    expect(res.status).toBe(500);
    expect(body.success).not.toBe(true);
    // 4 templates x 2 generation errors each.
    expect(body.failureCount).toBe(M * 2);
    const failures = body.failures as Array<{ message: string }>;
    expect(failures.some((f) => f.message.includes('no recurrenceRule'))).toBe(true);
  });

  it('is unchanged on a fully-successful run', async () => {
    h.generateDispatches.mockResolvedValue(CLEAN_RESULT);

    const { GET } = await import('@/app/api/cron/carrier-auto-dispatch/route');
    const res = await GET(cronRequest());
    const body = await res.json();

    expect(res.status).toBe(200);
    expect(body.success).toBe(true);
    expect(body.orgs_processed).toBe(1);
    expect(body.total_errors).toBe(0);
    expect(body.failureCount).toBe(0);
    expect(Array.isArray(body.details)).toBe(true);
  });
});
