-- CONSOLIDATED FIX MIGRATION (draft — review before applying)
-- Generated by: apps/web/scripts/audit/full-schema-drift-scan.ts
-- Generated at: 2026-06-02T22:24:50.179Z
-- DO NOT APPLY without reviewing each ALTER TABLE statement.

BEGIN;

-- No missing columns detected — no ALTER TABLE statements needed.

COMMIT;