-- CONSOLIDATED FIX MIGRATION (draft — review before applying)
-- Generated by: apps/web/scripts/audit/full-schema-drift-scan.ts
-- Generated at: 2026-05-30T21:43:45.038Z
-- DO NOT APPLY without reviewing each ALTER TABLE statement.

BEGIN;

-- Model: Route (table: Route)
ALTER TABLE public."Route" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMPTZ NULL;
ALTER TABLE public."Route" ADD COLUMN IF NOT EXISTS "deletedById" UUID NULL;

-- Model: CarrierClient (table: clients)
ALTER TABLE public."clients" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."clients" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierContract (table: contracts)
ALTER TABLE public."contracts" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."contracts" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierDriver (table: carrier_drivers)
ALTER TABLE public."carrier_drivers" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."carrier_drivers" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierTruck (table: carrier_trucks)
ALTER TABLE public."carrier_trucks" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."carrier_trucks" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierLoad (table: loads)
ALTER TABLE public."loads" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."loads" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

COMMIT;