/**
 * generic-csv.golden.test.ts — Golden file tests for the Generic CSV exporter.
 *
 * Each test generates output from the exporter and compares byte-for-byte
 * against a golden fixture file. Goldens are generated by generate-goldens.ts
 * and committed alongside the tests.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import { genericCsvExporter } from '../../exporters/generic-csv';
import { w2Settlement, c1099Settlement } from './__fixtures__/settlements.fixture';

const FIXTURES = join(__dirname, '__fixtures__');

async function streamToString(stream: Readable): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of stream) {
    chunks.push(Buffer.from(chunk as string | Buffer));
  }
  return Buffer.concat(chunks).toString('utf8');
}

describe('genericCsvExporter golden', () => {
  it('matches golden for W-2 + 1099 combined input', async () => {
    const stream = genericCsvExporter.build([w2Settlement, c1099Settlement]);
    const actual = await streamToString(stream);
    const expected = readFileSync(join(FIXTURES, 'generic-csv.golden.csv'), 'utf8');
    expect(actual).toBe(expected);
  });

  it('handles 1099-only input — produces one data row', async () => {
    const stream = genericCsvExporter.build([c1099Settlement]);
    const actual = await streamToString(stream);
    const lines = actual.split('\n').filter(Boolean);
    // Header + 1 data row
    expect(lines).toHaveLength(2);
    expect(lines[1]).toContain('FIRST_1099');
    expect(lines[1]).toContain('OWNER_OPERATOR_1099');
  });

  it('handles W-2-only input — produces one data row', async () => {
    const stream = genericCsvExporter.build([w2Settlement]);
    const actual = await streamToString(stream);
    const lines = actual.split('\n').filter(Boolean);
    expect(lines).toHaveLength(2);
    expect(lines[1]).toContain('FIRST_W2');
    expect(lines[1]).toContain('W2_EMPLOYEE');
  });

  it('handles empty input — produces header only', async () => {
    const stream = genericCsvExporter.build([]);
    const actual = await streamToString(stream);
    const lines = actual.split('\n').filter(Boolean);
    expect(lines).toHaveLength(1);
    expect(lines[0]).toContain('settlement_reference');
  });

  it('includes quantity>1 fixture (1099 has qty=2 components)', async () => {
    // The 1099 fixture has two components each with quantity=2
    // The exporter should count them correctly (line_count=2 for 1099 fixture)
    const stream = genericCsvExporter.build([c1099Settlement]);
    const actual = await streamToString(stream);
    expect(actual).toContain(',2,'); // line_count = 2 (two pay components)
    expect(actual).toContain(',1,'); // deduction_count = 1
  });

  it('includes deduction in output (negative gross_amount handled)', async () => {
    const stream = genericCsvExporter.build([w2Settlement]);
    const actual = await streamToString(stream);
    // deduction_count = 2, bonus_count = 2
    expect(actual).toContain(',3,2,2'); // line_count=3, bonus_count=2, deduction_count=2
  });

  it('build() returns a Readable', () => {
    const stream = genericCsvExporter.build([w2Settlement]);
    expect(stream).toBeInstanceOf(Readable);
  });
});
