'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { StopBuilder, type StopBuilderStop } from '@/components/carrier/stops/StopBuilder';
import { saveRouteTemplate } from '@/actions/carrier/save-route-template';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RouteTemplateFormData {
  id: string;
  templateName: string;
  clientId: string;
  contractId: string | null;
  scheduleType: string;
  recurrenceRule: string | null;
  recurrenceTimezone: string;
  scheduledDepartureTime: string | null;
  equipmentType: string;
  tempMinF: number | null;
  tempMaxF: number | null;
  maxWeightLbs: number | null;
  commodityDescription: string | null;
  defaultDriverId: string | null;
  defaultTruckId: string | null;
  autoGenerateDaysAhead: number;
  notes: string | null;
  stops: StopBuilderStop[];
}

interface RouteTemplateFormProps {
  initialData?: RouteTemplateFormData;
  templateId?: string;
}

interface ClientItem {
  id: string;
  name: string;
}

interface ContractItem {
  id: string;
  contractNumber: string;
  contractName: string | null;
}

interface DriverItem {
  id: string;
  firstName: string;
  lastName: string;
}

interface TruckItem {
  id: string;
  unitNumber: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const EQUIPMENT_TYPES = [
  { value: 'dry_van', label: 'Dry Van' },
  { value: 'flatbed', label: 'Flatbed' },
  { value: 'reefer', label: 'Reefer' },
  { value: 'tanker', label: 'Tanker' },
  { value: 'step_deck', label: 'Step Deck' },
  { value: 'other', label: 'Other' },
];

const SCHEDULE_TYPES = [
  { value: 'fixed_days', label: 'Fixed Days' },
  { value: 'frequency', label: 'Frequency' },
  { value: 'on_call', label: 'On Call' },
];

const TIMEZONES = [
  { value: 'America/New_York', label: 'Eastern (ET)' },
  { value: 'America/Chicago', label: 'Central (CT)' },
  { value: 'America/Denver', label: 'Mountain (MT)' },
  { value: 'America/Los_Angeles', label: 'Pacific (PT)' },
  { value: 'America/Phoenix', label: 'Arizona (AZ)' },
  { value: 'America/Anchorage', label: 'Alaska (AKT)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii (HT)' },
  { value: 'UTC', label: 'UTC' },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function RouteTemplateForm({ initialData, templateId }: RouteTemplateFormProps) {
  const router = useRouter();
  const isEdit = Boolean(templateId);

  // Form state
  const [templateName, setTemplateName] = useState(initialData?.templateName ?? '');
  const [clientId, setClientId] = useState(initialData?.clientId ?? '');
  const [contractId, setContractId] = useState(initialData?.contractId ?? '');
  const [scheduleType, setScheduleType] = useState(initialData?.scheduleType ?? 'fixed_days');
  // RRULE builder state
  const [recurrenceRule, setRecurrenceRule] = useState(initialData?.recurrenceRule ?? '');
  const [rruleFrequency, setRruleFrequency] = useState<'DAILY' | 'WEEKLY' | 'MONTHLY'>(() => {
    const rule = initialData?.recurrenceRule ?? '';
    if (rule.includes('FREQ=MONTHLY')) return 'MONTHLY';
    if (rule.includes('FREQ=DAILY')) return 'DAILY';
    return 'WEEKLY';
  });
  const [rruleSelectedDays, setRruleSelectedDays] = useState<string[]>(() => {
    const rule = initialData?.recurrenceRule ?? '';
    const match = rule.match(/BYDAY=([^;]+)/);
    if (!match) return [];
    return match[1].split(',').map((d) => d.trim().toUpperCase());
  });
  const [rruleMonthlyDays, setRruleMonthlyDays] = useState<string>(() => {
    const rule = initialData?.recurrenceRule ?? '';
    const match = rule.match(/BYMONTHDAY=([^;]+)/);
    return match ? match[1] : '';
  });
  const [recurrenceTimezone, setRecurrenceTimezone] = useState(
    initialData?.recurrenceTimezone ?? 'America/Chicago'
  );
  const [scheduledDepartureTime, setScheduledDepartureTime] = useState(
    initialData?.scheduledDepartureTime ?? ''
  );
  const [equipmentType, setEquipmentType] = useState(initialData?.equipmentType ?? '');
  const [tempMinF, setTempMinF] = useState(
    initialData?.tempMinF != null ? String(initialData.tempMinF) : ''
  );
  const [tempMaxF, setTempMaxF] = useState(
    initialData?.tempMaxF != null ? String(initialData.tempMaxF) : ''
  );
  const [maxWeightLbs, setMaxWeightLbs] = useState(
    initialData?.maxWeightLbs != null ? String(initialData.maxWeightLbs) : ''
  );
  const [commodityDescription, setCommodityDescription] = useState(
    initialData?.commodityDescription ?? ''
  );
  const [defaultDriverId, setDefaultDriverId] = useState(initialData?.defaultDriverId ?? '');
  const [defaultTruckId, setDefaultTruckId] = useState(initialData?.defaultTruckId ?? '');
  const [autoGenerateDaysAhead, setAutoGenerateDaysAhead] = useState(
    String(initialData?.autoGenerateDaysAhead ?? 7)
  );
  const [notes, setNotes] = useState(initialData?.notes ?? '');
  const [stops, setStops] = useState<StopBuilderStop[]>(initialData?.stops ?? []);

  // Auto-generate RRULE string from builder state
  useEffect(() => {
    if (scheduleType !== 'fixed_days' && scheduleType !== 'frequency') return;
    if (rruleFrequency === 'DAILY') {
      setRecurrenceRule('FREQ=DAILY');
    } else if (rruleFrequency === 'WEEKLY') {
      if (rruleSelectedDays.length === 0) {
        setRecurrenceRule('FREQ=WEEKLY');
      } else {
        setRecurrenceRule(`FREQ=WEEKLY;BYDAY=${rruleSelectedDays.join(',')}`);
      }
    } else if (rruleFrequency === 'MONTHLY') {
      if (rruleMonthlyDays.trim()) {
        setRecurrenceRule(`FREQ=MONTHLY;BYMONTHDAY=${rruleMonthlyDays.trim()}`);
      } else {
        setRecurrenceRule('FREQ=MONTHLY');
      }
    }
  }, [scheduleType, rruleFrequency, rruleSelectedDays, rruleMonthlyDays]);

  // Remote data
  const [clients, setClients] = useState<ClientItem[]>([]);
  const [contracts, setContracts] = useState<ContractItem[]>([]);
  const [drivers, setDrivers] = useState<DriverItem[]>([]);
  const [trucks, setTrucks] = useState<TruckItem[]>([]);

  // UI state
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Fetch clients
  useEffect(() => {
    async function loadClients() {
      try {
        const res = await fetch('/api/v1/carrier/clients?pageSize=200');
        if (!res.ok) return;
        const data = await res.json();
        setClients((data.data?.items ?? []) as ClientItem[]);
      } catch {
        // Ignore
      }
    }
    loadClients();
  }, []);

  // Fetch contracts when client changes
  useEffect(() => {
    if (!clientId) {
      setContracts([]);
      setContractId('');
      return;
    }
    async function loadContracts() {
      try {
        const res = await fetch(`/api/v1/carrier/contracts?client_id=${clientId}&pageSize=100`);
        if (!res.ok) return;
        const data = await res.json();
        setContracts((data.data?.items ?? []) as ContractItem[]);
      } catch {
        // Ignore
      }
    }
    loadContracts();
  }, [clientId]);

  // Fetch active drivers
  useEffect(() => {
    async function loadDrivers() {
      try {
        const res = await fetch('/api/v1/carrier/fleet/drivers?status=active&pageSize=200');
        if (!res.ok) return;
        const data = await res.json();
        setDrivers((data.data?.items ?? []) as DriverItem[]);
      } catch {
        // Ignore
      }
    }
    loadDrivers();
  }, []);

  // Fetch active trucks
  useEffect(() => {
    async function loadTrucks() {
      try {
        const res = await fetch('/api/v1/carrier/fleet/trucks?status=active&pageSize=200');
        if (!res.ok) return;
        const data = await res.json();
        setTrucks((data.data?.items ?? []) as TruckItem[]);
      } catch {
        // Ignore
      }
    }
    loadTrucks();
  }, []);

  function handleClientChange(val: string) {
    setClientId(val);
    setContractId('');
    if (errors.clientId) setErrors((e) => ({ ...e, clientId: '' }));
  }

  function validate(): boolean {
    const newErrors: Record<string, string> = {};
    if (!templateName.trim()) newErrors.templateName = 'Template name is required';
    if (!clientId) newErrors.clientId = 'Client is required';
    if (!equipmentType) newErrors.equipmentType = 'Equipment type is required';
    if (!scheduleType) newErrors.scheduleType = 'Schedule type is required';
    if (stops.length === 0) newErrors.stops = 'At least one stop is required';
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    setIsSubmitting(true);
    try {
      const result = await saveRouteTemplate({
        templateId,
        templateName: templateName.trim(),
        clientId,
        contractId: contractId || undefined,
        scheduleType,
        recurrenceRule: recurrenceRule || undefined,
        recurrenceTimezone,
        scheduledDepartureTime: scheduledDepartureTime || undefined,
        equipmentType,
        tempMinF: tempMinF ? Number(tempMinF) : undefined,
        tempMaxF: tempMaxF ? Number(tempMaxF) : undefined,
        maxWeightLbs: maxWeightLbs ? Number(maxWeightLbs) : undefined,
        commodityDescription: commodityDescription || undefined,
        defaultDriverId: defaultDriverId || undefined,
        defaultTruckId: defaultTruckId || undefined,
        autoGenerateDaysAhead: autoGenerateDaysAhead ? Number(autoGenerateDaysAhead) : undefined,
        notes: notes || undefined,
        stops,
      });

      if (!result.success) {
        toast.error(result.error ?? 'Failed to save template');
        return;
      }

      toast.success(isEdit ? 'Template updated' : 'Template created');
      if (!isEdit && result.templateId) {
        router.push(`/carrier/templates/${result.templateId}`);
      } else {
        router.refresh();
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Edit mode warning banner */}
      {isEdit && (
        <div className="flex items-start gap-3 rounded-lg border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-950 p-4">
          <AlertTriangle className="h-5 w-5 shrink-0 text-yellow-600 dark:text-yellow-400 mt-0.5" />
          <p className="text-sm text-yellow-800 dark:text-yellow-200">
            Changes to this template will only apply to future auto-generated dispatches. Existing
            dispatches are not affected.
          </p>
        </div>
      )}

      {/* Two-panel layout */}
      <div className="flex flex-col lg:flex-row gap-6">
        {/* LEFT PANEL — Metadata */}
        <div className="w-full lg:w-1/2 space-y-5">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            Template Details
          </h3>

          {/* Template name */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="templateName">
              Template Name <span className="text-destructive">*</span>
            </label>
            <Input
              id="templateName"
              value={templateName}
              onChange={(e) => {
                setTemplateName(e.target.value);
                if (errors.templateName) setErrors((er) => ({ ...er, templateName: '' }));
              }}
              placeholder="e.g. Chicago to Dallas — Mon/Wed/Fri"
            />
            {errors.templateName && (
              <p className="text-xs text-destructive">{errors.templateName}</p>
            )}
          </div>

          {/* Client */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="clientId">
              Client <span className="text-destructive">*</span>
            </label>
            <Select value={clientId || undefined} onValueChange={handleClientChange}>
              <SelectTrigger id="clientId">
                <SelectValue placeholder="Select client" />
              </SelectTrigger>
              <SelectContent>
                {clients.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {c.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.clientId && <p className="text-xs text-destructive">{errors.clientId}</p>}
          </div>

          {/* Contract */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="contractId">
              Contract <span className="text-muted-foreground text-xs">(optional)</span>
            </label>
            <Select
              value={contractId || undefined}
              onValueChange={(val) => setContractId(val)}
              disabled={!clientId || contracts.length === 0}
            >
              <SelectTrigger id="contractId">
                <SelectValue
                  placeholder={
                    !clientId
                      ? 'Select a client first'
                      : contracts.length === 0
                      ? 'No contracts for this client'
                      : 'Select contract'
                  }
                />
              </SelectTrigger>
              <SelectContent>
                {contracts.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    <span className="flex flex-col">
                      <span>{c.contractName || c.contractNumber}</span>
                      {c.contractName && (
                        <span className="text-xs text-muted-foreground font-mono">{c.contractNumber}</span>
                      )}
                    </span>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Schedule type */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="scheduleType">
              Schedule Type <span className="text-destructive">*</span>
            </label>
            <Select
              value={scheduleType}
              onValueChange={(val) => {
                setScheduleType(val);
                if (errors.scheduleType) setErrors((er) => ({ ...er, scheduleType: '' }));
              }}
            >
              <SelectTrigger id="scheduleType">
                <SelectValue placeholder="Select schedule type" />
              </SelectTrigger>
              <SelectContent>
                {SCHEDULE_TYPES.map((t) => (
                  <SelectItem key={t.value} value={t.value}>
                    {t.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.scheduleType && (
              <p className="text-xs text-destructive">{errors.scheduleType}</p>
            )}
          </div>

          {/* Recurrence rule builder — only shown for fixed_days and frequency */}
          {(scheduleType === 'fixed_days' || scheduleType === 'frequency') && (
            <>
              {/* Frequency selector */}
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="rruleFrequency">
                  Recurrence Frequency
                </label>
                <Select
                  value={rruleFrequency}
                  onValueChange={(val) => setRruleFrequency(val as 'DAILY' | 'WEEKLY' | 'MONTHLY')}
                >
                  <SelectTrigger id="rruleFrequency">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="DAILY">Daily</SelectItem>
                    <SelectItem value="WEEKLY">Weekly</SelectItem>
                    <SelectItem value="MONTHLY">Monthly</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Weekly day picker */}
              {rruleFrequency === 'WEEKLY' && (
                <div className="space-y-2">
                  <label className="text-sm font-medium text-foreground">Days of Week</label>
                  <div className="flex gap-1.5 flex-wrap">
                    {(['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'] as const).map((day) => {
                      const label = { MO: 'Mon', TU: 'Tue', WE: 'Wed', TH: 'Thu', FR: 'Fri', SA: 'Sat', SU: 'Sun' }[day];
                      const isActive = rruleSelectedDays.includes(day);
                      return (
                        <button
                          key={day}
                          type="button"
                          onClick={() =>
                            setRruleSelectedDays((prev) =>
                              isActive ? prev.filter((d) => d !== day) : [...prev, day]
                            )
                          }
                          className={`rounded-md px-3 py-1.5 text-sm font-medium transition-colors border ${
                            isActive
                              ? 'bg-primary text-primary-foreground border-primary'
                              : 'bg-muted text-muted-foreground border-border hover:bg-accent hover:text-accent-foreground'
                          }`}
                        >
                          {label}
                        </button>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* Monthly day picker */}
              {rruleFrequency === 'MONTHLY' && (
                <div className="space-y-1.5">
                  <label className="text-sm font-medium text-foreground" htmlFor="rruleMonthlyDays">
                    Days of Month
                  </label>
                  <Input
                    id="rruleMonthlyDays"
                    value={rruleMonthlyDays}
                    onChange={(e) => setRruleMonthlyDays(e.target.value)}
                    placeholder="e.g. 1,15"
                  />
                  <p className="text-xs text-muted-foreground">
                    Comma-separated day numbers (e.g. 1,15 for 1st and 15th of each month)
                  </p>
                </div>
              )}

              {/* Generated RRULE preview */}
              {recurrenceRule && (
                <p className="text-xs text-muted-foreground font-mono">
                  Generated: {recurrenceRule}
                </p>
              )}

              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="recurrenceTimezone">
                  Timezone
                </label>
                <Select value={recurrenceTimezone} onValueChange={setRecurrenceTimezone}>
                  <SelectTrigger id="recurrenceTimezone">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {TIMEZONES.map((tz) => (
                      <SelectItem key={tz.value} value={tz.value}>
                        {tz.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-1.5">
                <label
                  className="text-sm font-medium text-foreground"
                  htmlFor="scheduledDepartureTime"
                >
                  Scheduled Departure Time
                </label>
                <Input
                  id="scheduledDepartureTime"
                  type="time"
                  value={scheduledDepartureTime}
                  onChange={(e) => setScheduledDepartureTime(e.target.value)}
                />
              </div>
            </>
          )}

          {/* Equipment type */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="equipmentType">
              Equipment Type <span className="text-destructive">*</span>
            </label>
            <Select
              value={equipmentType || undefined}
              onValueChange={(val) => {
                setEquipmentType(val);
                if (errors.equipmentType) setErrors((er) => ({ ...er, equipmentType: '' }));
              }}
            >
              <SelectTrigger id="equipmentType">
                <SelectValue placeholder="Select equipment type" />
              </SelectTrigger>
              <SelectContent>
                {EQUIPMENT_TYPES.map((t) => (
                  <SelectItem key={t.value} value={t.value}>
                    {t.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.equipmentType && (
              <p className="text-xs text-destructive">{errors.equipmentType}</p>
            )}
          </div>

          {/* Reefer temp range */}
          {equipmentType === 'reefer' && (
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="tempMinF">
                  Min Temp (°F)
                </label>
                <Input
                  id="tempMinF"
                  type="number"
                  value={tempMinF}
                  onChange={(e) => setTempMinF(e.target.value)}
                  placeholder="e.g. 34"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="tempMaxF">
                  Max Temp (°F)
                </label>
                <Input
                  id="tempMaxF"
                  type="number"
                  value={tempMaxF}
                  onChange={(e) => setTempMaxF(e.target.value)}
                  placeholder="e.g. 40"
                />
              </div>
            </div>
          )}

          {/* Max weight */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="maxWeightLbs">
              Max Weight (lbs)
            </label>
            <Input
              id="maxWeightLbs"
              type="number"
              value={maxWeightLbs}
              onChange={(e) => setMaxWeightLbs(e.target.value)}
              placeholder="e.g. 44000"
            />
          </div>

          {/* Commodity */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="commodityDescription">
              Commodity Description
            </label>
            <Input
              id="commodityDescription"
              value={commodityDescription}
              onChange={(e) => setCommodityDescription(e.target.value)}
              placeholder="e.g. Dry goods"
            />
          </div>

          {/* Default driver / truck */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground" htmlFor="defaultDriverId">
                Default Driver <span className="text-muted-foreground text-xs">(optional)</span>
              </label>
              <Select
                value={defaultDriverId || '__none__'}
                onValueChange={(val) => setDefaultDriverId(val === '__none__' ? '' : val)}
              >
                <SelectTrigger id="defaultDriverId">
                  <SelectValue placeholder={drivers.length === 0 ? 'Loading...' : 'None'} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">None</SelectItem>
                  {drivers.map((d) => (
                    <SelectItem key={d.id} value={d.id}>
                      {d.firstName} {d.lastName}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground" htmlFor="defaultTruckId">
                Default Truck <span className="text-muted-foreground text-xs">(optional)</span>
              </label>
              <Select
                value={defaultTruckId || '__none__'}
                onValueChange={(val) => setDefaultTruckId(val === '__none__' ? '' : val)}
              >
                <SelectTrigger id="defaultTruckId">
                  <SelectValue placeholder={trucks.length === 0 ? 'Loading...' : 'None'} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">None</SelectItem>
                  {trucks.map((t) => (
                    <SelectItem key={t.id} value={t.id}>
                      {t.unitNumber}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* Auto generate days ahead */}
          <div className="space-y-1.5">
            <label
              className="text-sm font-medium text-foreground"
              htmlFor="autoGenerateDaysAhead"
            >
              Auto Generate Days Ahead
            </label>
            <Input
              id="autoGenerateDaysAhead"
              type="number"
              min={1}
              value={autoGenerateDaysAhead}
              onChange={(e) => setAutoGenerateDaysAhead(e.target.value)}
              placeholder="7"
            />
            <p className="text-xs text-muted-foreground">
              How many days in advance to auto-generate dispatches.
            </p>
          </div>

          {/* Notes */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="notes">
              Notes
            </label>
            <Textarea
              id="notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Additional notes about this template..."
              rows={3}
            />
          </div>
        </div>

        {/* RIGHT PANEL — Stops */}
        <div className="w-full lg:w-1/2 space-y-4">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            Route Stops
          </h3>
          {errors.stops && (
            <p className="text-xs text-destructive">{errors.stops}</p>
          )}
          <StopBuilder stops={stops} onChange={setStops} mode="template" />
        </div>
      </div>

      {/* Submit */}
      <div className="flex justify-end gap-3 pt-2 border-t border-border">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push('/carrier/templates')}
          disabled={isSubmitting}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          {isEdit ? 'Save Changes' : 'Create Template'}
        </Button>
      </div>
    </form>
  );
}
