'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertTriangle, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { StopBuilder, type StopBuilderStop } from '@/components/carrier/stops/StopBuilder';
import { saveRouteTemplate } from '@/actions/carrier/save-route-template';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RouteTemplateFormData {
  id: string;
  templateName: string;
  clientId: string;
  contractId: string | null;
  scheduleType: string;
  recurrenceRule: string | null;
  recurrenceTimezone: string;
  scheduledDepartureTime: string | null;
  equipmentType: string;
  tempMinF: number | null;
  tempMaxF: number | null;
  maxWeightLbs: number | null;
  commodityDescription: string | null;
  defaultDriverId: string | null;
  defaultTruckId: string | null;
  autoGenerateDaysAhead: number;
  notes: string | null;
  stops: StopBuilderStop[];
}

interface RouteTemplateFormProps {
  initialData?: RouteTemplateFormData;
  templateId?: string;
}

interface ClientItem {
  id: string;
  name: string;
}

interface ContractItem {
  id: string;
  contractNumber: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const EQUIPMENT_TYPES = [
  { value: 'dry_van', label: 'Dry Van' },
  { value: 'reefer', label: 'Reefer' },
  { value: 'flatbed', label: 'Flatbed' },
  { value: 'step_deck', label: 'Step Deck' },
  { value: 'tanker', label: 'Tanker' },
  { value: 'intermodal', label: 'Intermodal' },
  { value: 'power_only', label: 'Power Only' },
];

const SCHEDULE_TYPES = [
  { value: 'recurring', label: 'Recurring' },
  { value: 'on_demand', label: 'On Demand' },
  { value: 'seasonal', label: 'Seasonal' },
];

const TIMEZONES = [
  { value: 'America/New_York', label: 'Eastern (ET)' },
  { value: 'America/Chicago', label: 'Central (CT)' },
  { value: 'America/Denver', label: 'Mountain (MT)' },
  { value: 'America/Los_Angeles', label: 'Pacific (PT)' },
  { value: 'America/Phoenix', label: 'Arizona (AZ)' },
  { value: 'America/Anchorage', label: 'Alaska (AKT)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii (HT)' },
  { value: 'UTC', label: 'UTC' },
];

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function RouteTemplateForm({ initialData, templateId }: RouteTemplateFormProps) {
  const router = useRouter();
  const isEdit = Boolean(templateId);

  // Form state
  const [templateName, setTemplateName] = useState(initialData?.templateName ?? '');
  const [clientId, setClientId] = useState(initialData?.clientId ?? '');
  const [contractId, setContractId] = useState(initialData?.contractId ?? '');
  const [scheduleType, setScheduleType] = useState(initialData?.scheduleType ?? 'recurring');
  const [recurrenceRule, setRecurrenceRule] = useState(initialData?.recurrenceRule ?? '');
  const [recurrenceRuleError, setRecurrenceRuleError] = useState('');
  const [recurrenceTimezone, setRecurrenceTimezone] = useState(
    initialData?.recurrenceTimezone ?? 'America/Chicago'
  );
  const [scheduledDepartureTime, setScheduledDepartureTime] = useState(
    initialData?.scheduledDepartureTime ?? ''
  );
  const [equipmentType, setEquipmentType] = useState(initialData?.equipmentType ?? '');
  const [tempMinF, setTempMinF] = useState(
    initialData?.tempMinF != null ? String(initialData.tempMinF) : ''
  );
  const [tempMaxF, setTempMaxF] = useState(
    initialData?.tempMaxF != null ? String(initialData.tempMaxF) : ''
  );
  const [maxWeightLbs, setMaxWeightLbs] = useState(
    initialData?.maxWeightLbs != null ? String(initialData.maxWeightLbs) : ''
  );
  const [commodityDescription, setCommodityDescription] = useState(
    initialData?.commodityDescription ?? ''
  );
  const [defaultDriverId, setDefaultDriverId] = useState(initialData?.defaultDriverId ?? '');
  const [defaultTruckId, setDefaultTruckId] = useState(initialData?.defaultTruckId ?? '');
  const [autoGenerateDaysAhead, setAutoGenerateDaysAhead] = useState(
    String(initialData?.autoGenerateDaysAhead ?? 7)
  );
  const [notes, setNotes] = useState(initialData?.notes ?? '');
  const [stops, setStops] = useState<StopBuilderStop[]>(initialData?.stops ?? []);

  // Remote data
  const [clients, setClients] = useState<ClientItem[]>([]);
  const [contracts, setContracts] = useState<ContractItem[]>([]);

  // UI state
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Fetch clients
  useEffect(() => {
    async function loadClients() {
      try {
        const res = await fetch('/api/v1/carrier/clients?pageSize=200');
        if (!res.ok) return;
        const data = await res.json();
        setClients((data.data?.items ?? []) as ClientItem[]);
      } catch {
        // Ignore
      }
    }
    loadClients();
  }, []);

  // Fetch contracts when client changes
  useEffect(() => {
    if (!clientId) {
      setContracts([]);
      setContractId('');
      return;
    }
    async function loadContracts() {
      try {
        const res = await fetch(`/api/v1/carrier/contracts?client_id=${clientId}&pageSize=100`);
        if (!res.ok) return;
        const data = await res.json();
        setContracts((data.data?.items ?? []) as ContractItem[]);
      } catch {
        // Ignore
      }
    }
    loadContracts();
  }, [clientId]);

  function handleClientChange(val: string) {
    setClientId(val);
    setContractId('');
    if (errors.clientId) setErrors((e) => ({ ...e, clientId: '' }));
  }

  function handleRecurrenceRuleBlur() {
    if (recurrenceRule && !recurrenceRule.startsWith('FREQ=')) {
      setRecurrenceRuleError('Must start with FREQ=');
    } else {
      setRecurrenceRuleError('');
    }
  }

  function validate(): boolean {
    const newErrors: Record<string, string> = {};
    if (!templateName.trim()) newErrors.templateName = 'Template name is required';
    if (!clientId) newErrors.clientId = 'Client is required';
    if (!equipmentType) newErrors.equipmentType = 'Equipment type is required';
    if (!scheduleType) newErrors.scheduleType = 'Schedule type is required';
    if (recurrenceRule && !recurrenceRule.startsWith('FREQ=')) {
      newErrors.recurrenceRule = 'Must start with FREQ=';
    }
    if (stops.length === 0) newErrors.stops = 'At least one stop is required';
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    setIsSubmitting(true);
    try {
      const result = await saveRouteTemplate({
        templateId,
        templateName: templateName.trim(),
        clientId,
        contractId: contractId || undefined,
        scheduleType,
        recurrenceRule: recurrenceRule || undefined,
        recurrenceTimezone,
        scheduledDepartureTime: scheduledDepartureTime || undefined,
        equipmentType,
        tempMinF: tempMinF ? Number(tempMinF) : undefined,
        tempMaxF: tempMaxF ? Number(tempMaxF) : undefined,
        maxWeightLbs: maxWeightLbs ? Number(maxWeightLbs) : undefined,
        commodityDescription: commodityDescription || undefined,
        defaultDriverId: defaultDriverId || undefined,
        defaultTruckId: defaultTruckId || undefined,
        autoGenerateDaysAhead: autoGenerateDaysAhead ? Number(autoGenerateDaysAhead) : undefined,
        notes: notes || undefined,
        stops,
      });

      if (!result.success) {
        toast.error(result.error ?? 'Failed to save template');
        return;
      }

      toast.success(isEdit ? 'Template updated' : 'Template created');
      if (!isEdit && result.templateId) {
        router.push(`/carrier/templates/${result.templateId}`);
      } else {
        router.refresh();
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : 'Something went wrong');
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {/* Edit mode warning banner */}
      {isEdit && (
        <div className="flex items-start gap-3 rounded-lg border border-yellow-200 dark:border-yellow-800 bg-yellow-50 dark:bg-yellow-950 p-4">
          <AlertTriangle className="h-5 w-5 shrink-0 text-yellow-600 dark:text-yellow-400 mt-0.5" />
          <p className="text-sm text-yellow-800 dark:text-yellow-200">
            Changes to this template will only apply to future auto-generated dispatches. Existing
            dispatches are not affected.
          </p>
        </div>
      )}

      {/* Two-panel layout */}
      <div className="flex flex-col lg:flex-row gap-6">
        {/* LEFT PANEL — Metadata */}
        <div className="w-full lg:w-1/2 space-y-5">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            Template Details
          </h3>

          {/* Template name */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="templateName">
              Template Name <span className="text-destructive">*</span>
            </label>
            <Input
              id="templateName"
              value={templateName}
              onChange={(e) => {
                setTemplateName(e.target.value);
                if (errors.templateName) setErrors((er) => ({ ...er, templateName: '' }));
              }}
              placeholder="e.g. Chicago to Dallas — Mon/Wed/Fri"
            />
            {errors.templateName && (
              <p className="text-xs text-destructive">{errors.templateName}</p>
            )}
          </div>

          {/* Client */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="clientId">
              Client <span className="text-destructive">*</span>
            </label>
            <Select value={clientId || undefined} onValueChange={handleClientChange}>
              <SelectTrigger id="clientId">
                <SelectValue placeholder="Select client" />
              </SelectTrigger>
              <SelectContent>
                {clients.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {c.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.clientId && <p className="text-xs text-destructive">{errors.clientId}</p>}
          </div>

          {/* Contract */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="contractId">
              Contract <span className="text-muted-foreground text-xs">(optional)</span>
            </label>
            <Select
              value={contractId || undefined}
              onValueChange={(val) => setContractId(val)}
              disabled={!clientId || contracts.length === 0}
            >
              <SelectTrigger id="contractId">
                <SelectValue
                  placeholder={
                    !clientId
                      ? 'Select a client first'
                      : contracts.length === 0
                      ? 'No contracts for this client'
                      : 'Select contract'
                  }
                />
              </SelectTrigger>
              <SelectContent>
                {contracts.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {c.contractNumber}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Schedule type */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="scheduleType">
              Schedule Type <span className="text-destructive">*</span>
            </label>
            <Select
              value={scheduleType}
              onValueChange={(val) => {
                setScheduleType(val);
                if (errors.scheduleType) setErrors((er) => ({ ...er, scheduleType: '' }));
              }}
            >
              <SelectTrigger id="scheduleType">
                <SelectValue placeholder="Select schedule type" />
              </SelectTrigger>
              <SelectContent>
                {SCHEDULE_TYPES.map((t) => (
                  <SelectItem key={t.value} value={t.value}>
                    {t.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.scheduleType && (
              <p className="text-xs text-destructive">{errors.scheduleType}</p>
            )}
          </div>

          {/* Recurrence rule — only shown for recurring */}
          {scheduleType === 'recurring' && (
            <>
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="recurrenceRule">
                  Recurrence Rule
                </label>
                <Input
                  id="recurrenceRule"
                  value={recurrenceRule}
                  onChange={(e) => {
                    setRecurrenceRule(e.target.value);
                    setRecurrenceRuleError('');
                    if (errors.recurrenceRule) setErrors((er) => ({ ...er, recurrenceRule: '' }));
                  }}
                  onBlur={handleRecurrenceRuleBlur}
                  placeholder="e.g. FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR"
                />
                <p className="text-xs text-muted-foreground">
                  RRULE format, e.g. FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
                </p>
                {(recurrenceRuleError || errors.recurrenceRule) && (
                  <p className="text-xs text-destructive">
                    {recurrenceRuleError || errors.recurrenceRule}
                  </p>
                )}
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="recurrenceTimezone">
                  Timezone
                </label>
                <Select value={recurrenceTimezone} onValueChange={setRecurrenceTimezone}>
                  <SelectTrigger id="recurrenceTimezone">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {TIMEZONES.map((tz) => (
                      <SelectItem key={tz.value} value={tz.value}>
                        {tz.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-1.5">
                <label
                  className="text-sm font-medium text-foreground"
                  htmlFor="scheduledDepartureTime"
                >
                  Scheduled Departure Time
                </label>
                <Input
                  id="scheduledDepartureTime"
                  type="time"
                  value={scheduledDepartureTime}
                  onChange={(e) => setScheduledDepartureTime(e.target.value)}
                />
              </div>
            </>
          )}

          {/* Equipment type */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="equipmentType">
              Equipment Type <span className="text-destructive">*</span>
            </label>
            <Select
              value={equipmentType || undefined}
              onValueChange={(val) => {
                setEquipmentType(val);
                if (errors.equipmentType) setErrors((er) => ({ ...er, equipmentType: '' }));
              }}
            >
              <SelectTrigger id="equipmentType">
                <SelectValue placeholder="Select equipment type" />
              </SelectTrigger>
              <SelectContent>
                {EQUIPMENT_TYPES.map((t) => (
                  <SelectItem key={t.value} value={t.value}>
                    {t.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.equipmentType && (
              <p className="text-xs text-destructive">{errors.equipmentType}</p>
            )}
          </div>

          {/* Reefer temp range */}
          {equipmentType === 'reefer' && (
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="tempMinF">
                  Min Temp (°F)
                </label>
                <Input
                  id="tempMinF"
                  type="number"
                  value={tempMinF}
                  onChange={(e) => setTempMinF(e.target.value)}
                  placeholder="e.g. 34"
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-medium text-foreground" htmlFor="tempMaxF">
                  Max Temp (°F)
                </label>
                <Input
                  id="tempMaxF"
                  type="number"
                  value={tempMaxF}
                  onChange={(e) => setTempMaxF(e.target.value)}
                  placeholder="e.g. 40"
                />
              </div>
            </div>
          )}

          {/* Max weight */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="maxWeightLbs">
              Max Weight (lbs)
            </label>
            <Input
              id="maxWeightLbs"
              type="number"
              value={maxWeightLbs}
              onChange={(e) => setMaxWeightLbs(e.target.value)}
              placeholder="e.g. 44000"
            />
          </div>

          {/* Commodity */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="commodityDescription">
              Commodity Description
            </label>
            <Input
              id="commodityDescription"
              value={commodityDescription}
              onChange={(e) => setCommodityDescription(e.target.value)}
              placeholder="e.g. Dry goods"
            />
          </div>

          {/* Default driver/truck — text inputs (no API endpoint available) */}
          {/* TODO: Replace with proper selects once /api/v1/carrier/drivers exists */}
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground" htmlFor="defaultDriverId">
                Default Driver ID
                <span className="ml-1 text-xs text-muted-foreground">(UUID, optional)</span>
              </label>
              <Input
                id="defaultDriverId"
                value={defaultDriverId}
                onChange={(e) => setDefaultDriverId(e.target.value)}
                placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground" htmlFor="defaultTruckId">
                Default Truck ID
                <span className="ml-1 text-xs text-muted-foreground">(UUID, optional)</span>
              </label>
              <Input
                id="defaultTruckId"
                value={defaultTruckId}
                onChange={(e) => setDefaultTruckId(e.target.value)}
                placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              />
            </div>
          </div>

          {/* Auto generate days ahead */}
          <div className="space-y-1.5">
            <label
              className="text-sm font-medium text-foreground"
              htmlFor="autoGenerateDaysAhead"
            >
              Auto Generate Days Ahead
            </label>
            <Input
              id="autoGenerateDaysAhead"
              type="number"
              min={1}
              value={autoGenerateDaysAhead}
              onChange={(e) => setAutoGenerateDaysAhead(e.target.value)}
              placeholder="7"
            />
            <p className="text-xs text-muted-foreground">
              How many days in advance to auto-generate dispatches.
            </p>
          </div>

          {/* Notes */}
          <div className="space-y-1.5">
            <label className="text-sm font-medium text-foreground" htmlFor="notes">
              Notes
            </label>
            <Textarea
              id="notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Additional notes about this template..."
              rows={3}
            />
          </div>
        </div>

        {/* RIGHT PANEL — Stops */}
        <div className="w-full lg:w-1/2 space-y-4">
          <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            Route Stops
          </h3>
          {errors.stops && (
            <p className="text-xs text-destructive">{errors.stops}</p>
          )}
          <StopBuilder stops={stops} onChange={setStops} mode="template" />
        </div>
      </div>

      {/* Submit */}
      <div className="flex justify-end gap-3 pt-2 border-t border-border">
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push('/carrier/templates')}
          disabled={isSubmitting}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
          {isEdit ? 'Save Changes' : 'Create Template'}
        </Button>
      </div>
    </form>
  );
}
