-- Migration: add_soft_delete_columns_drift_fix
-- Generated by: apps/web/scripts/audit/full-schema-drift-scan.ts (quick-417)
-- Applied by: quick-418
-- Adds 12 missing soft-delete columns across 6 models that exist in schema.prisma
-- but were absent from the live database, causing P2022 errors.
-- All columns are NULL — no default, no backfill required.

BEGIN;

-- Model: Route (table: Route)
ALTER TABLE public."Route" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMPTZ NULL;
ALTER TABLE public."Route" ADD COLUMN IF NOT EXISTS "deletedById" UUID NULL;

-- Model: CarrierClient (table: clients)
ALTER TABLE public."clients" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."clients" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierContract (table: contracts)
ALTER TABLE public."contracts" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."contracts" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierDriver (table: carrier_drivers)
ALTER TABLE public."carrier_drivers" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."carrier_drivers" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierTruck (table: carrier_trucks)
ALTER TABLE public."carrier_trucks" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."carrier_trucks" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Model: CarrierLoad (table: loads)
ALTER TABLE public."loads" ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMPTZ NULL;
ALTER TABLE public."loads" ADD COLUMN IF NOT EXISTS "deleted_by_id" UUID NULL;

-- Self-validation: verify all 12 columns now exist before committing
DO $$
DECLARE
  missing_cols TEXT := '';
BEGIN
  -- Route
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='Route' AND column_name='deletedAt') THEN
    missing_cols := missing_cols || 'Route.deletedAt, ';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='Route' AND column_name='deletedById') THEN
    missing_cols := missing_cols || 'Route.deletedById, ';
  END IF;
  -- clients
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='clients' AND column_name='deleted_at') THEN
    missing_cols := missing_cols || 'clients.deleted_at, ';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='clients' AND column_name='deleted_by_id') THEN
    missing_cols := missing_cols || 'clients.deleted_by_id, ';
  END IF;
  -- contracts
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='contracts' AND column_name='deleted_at') THEN
    missing_cols := missing_cols || 'contracts.deleted_at, ';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='contracts' AND column_name='deleted_by_id') THEN
    missing_cols := missing_cols || 'contracts.deleted_by_id, ';
  END IF;
  -- carrier_drivers
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='carrier_drivers' AND column_name='deleted_at') THEN
    missing_cols := missing_cols || 'carrier_drivers.deleted_at, ';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='carrier_drivers' AND column_name='deleted_by_id') THEN
    missing_cols := missing_cols || 'carrier_drivers.deleted_by_id, ';
  END IF;
  -- carrier_trucks
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='carrier_trucks' AND column_name='deleted_at') THEN
    missing_cols := missing_cols || 'carrier_trucks.deleted_at, ';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='carrier_trucks' AND column_name='deleted_by_id') THEN
    missing_cols := missing_cols || 'carrier_trucks.deleted_by_id, ';
  END IF;
  -- loads
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='loads' AND column_name='deleted_at') THEN
    missing_cols := missing_cols || 'loads.deleted_at, ';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='loads' AND column_name='deleted_by_id') THEN
    missing_cols := missing_cols || 'loads.deleted_by_id, ';
  END IF;

  IF missing_cols <> '' THEN
    RAISE EXCEPTION 'Schema drift fix incomplete — columns still missing after ALTER: %', rtrim(missing_cols, ', ');
  END IF;
END $$;

COMMIT;
