import { z } from 'zod';
import { FeatureSchema, type Feature } from './feature-registry-schema';

/**
 * Feature Registry — Single source of truth for user-facing features
 *
 * HOW TO ADD A NEW FEATURE:
 * 1. Append entry to `rawFeatures` array below with all required fields
 * 2. Create docs-content/client/{slug}.mdx (unless requiresClientDoc: false)
 * 3. Create docs-content/sysadmin/{slug}.mdx (unless requiresSysadminDoc: false)
 * 4. Open PR — CI will block if required docs are missing
 */

const rawFeatures = [
  // ============================================================
  // OWNER PORTAL - Carrier Ops
  // ============================================================
  {
    slug: 'carrier-dashboard',
    name: 'Carrier Dashboard',
    shortDescription:
      'Operations dashboard with KPIs, load status, driver availability, and fleet health metrics.',
    portal: 'owner',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/dashboard',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-loads', 'carrier-fleet-drivers'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/dashboard.ts'],
    prismaModels: ['Load', 'Route', 'Driver', 'Truck'],
  },
  {
    slug: 'carrier-clients',
    name: 'Client Management',
    shortDescription:
      'Manage shippers and brokers with contact info, load history, and revenue tracking.',
    portal: 'owner',
    category: 'crm',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/clients',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-contracts', 'crm'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/clients.ts'],
    prismaModels: ['Customer'],
  },
  {
    slug: 'carrier-contracts',
    name: 'Contract Management',
    shortDescription:
      'Create and manage carrier contracts with templates, rate tables, and renewal tracking.',
    portal: 'owner',
    category: 'crm',
    planTier: 'business',
    status: 'stable',
    route: '/carrier/contracts',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-clients', 'carrier-templates'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/contracts.ts'],
    prismaModels: ['Contract'],
  },
  {
    slug: 'carrier-templates',
    name: 'Dispatch Templates',
    shortDescription:
      'Reusable dispatch and route templates for common lanes and workflows.',
    portal: 'owner',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/templates',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-dispatches', 'routes'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/templates.ts'],
    prismaModels: ['DispatchTemplate'],
  },
  {
    slug: 'carrier-dispatches',
    name: 'Dispatch Board',
    shortDescription:
      'Ready-to-dispatch workflow with drag-and-drop assignment, driver availability, and truck status.',
    portal: 'owner',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/dispatches',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-loads', 'routes'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/dispatches.ts'],
    prismaModels: ['Route', 'RouteStop', 'Load'],
  },
  {
    slug: 'carrier-loads',
    name: 'Carrier Load Management',
    shortDescription:
      'Load creation, status workflow, route assignment, and tracking from PENDING to DELIVERED.',
    portal: 'owner',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/loads',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-dispatches', 'routes', 'driver-my-load'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/loads.ts'],
    prismaModels: ['Load', 'RouteStop'],
  },
  {
    slug: 'carrier-messages',
    name: 'Fleet Messaging',
    shortDescription:
      'iMessage-style fleet communication with broadcast and targeted messaging, unread badges, and push notifications.',
    portal: 'owner',
    category: 'fleet',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/messages',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['driver-messages'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/messages.ts'],
    prismaModels: ['FleetMessage'],
  },
  {
    slug: 'carrier-fleet-drivers',
    name: 'Carrier Driver Management',
    shortDescription:
      'Driver list with compliance tracking, document expiry dots, current load status, and invitations.',
    portal: 'owner',
    category: 'fleet',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/fleet/drivers',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['drivers', 'driver-documents'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/drivers.ts'],
    prismaModels: ['Driver', 'User'],
  },
  {
    slug: 'carrier-fleet-trucks',
    name: 'Carrier Truck Management',
    shortDescription:
      'Truck fleet management with status badges, document tracking, maintenance schedules, and safety alerts.',
    portal: 'owner',
    category: 'fleet',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/fleet/trucks',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['trucks'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/trucks.ts'],
    prismaModels: ['Truck', 'Document'],
  },
  {
    slug: 'carrier-facilities',
    name: 'Facility Management',
    shortDescription:
      'Manage yards, warehouses, and terminals with geofencing and driver check-in tracking.',
    portal: 'owner',
    category: 'fleet',
    planTier: 'business',
    status: 'stable',
    route: '/carrier/facilities',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-stops'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/facilities.ts'],
    prismaModels: ['Facility'],
  },
  {
    slug: 'carrier-stops',
    name: 'Stop Management',
    shortDescription:
      'Manage route stops with pickup/delivery details, contact info, BOL/PO numbers, and load linkage.',
    portal: 'owner',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/carrier/stops',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['routes', 'carrier-loads'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/stops.ts'],
    prismaModels: ['RouteStop'],
  },
  {
    slug: 'carrier-reports-revenue',
    name: 'Revenue Report',
    shortDescription:
      'Revenue analytics by customer, lane, driver, and time period with trend charts.',
    portal: 'owner',
    category: 'reporting',
    planTier: 'business',
    status: 'stable',
    route: '/carrier/reports/revenue',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['invoices', 'lane-analytics'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/reports.ts'],
    prismaModels: ['Invoice', 'Load'],
  },
  {
    slug: 'carrier-reports-driver-pay',
    name: 'Driver Pay Report',
    shortDescription:
      'Driver payroll summary with miles, loads, bonuses, deductions, and pay period totals.',
    portal: 'owner',
    category: 'reporting',
    planTier: 'business',
    status: 'stable',
    route: '/carrier/reports/driver-pay',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['payroll'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/reports.ts'],
    prismaModels: ['PayrollRecord'],
  },
  {
    slug: 'carrier-reports-aging',
    name: 'AR Aging Report',
    shortDescription:
      'Accounts receivable aging by customer with 30/60/90 day buckets and overdue alerts.',
    portal: 'owner',
    category: 'reporting',
    planTier: 'business',
    status: 'stable',
    route: '/carrier/reports/aging',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['invoices'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/reports.ts'],
    prismaModels: ['Invoice'],
  },
  {
    slug: 'carrier-reports-performance',
    name: 'Performance Report',
    shortDescription:
      'Fleet performance metrics: on-time delivery, utilization, cost-per-mile, and driver efficiency.',
    portal: 'owner',
    category: 'reporting',
    planTier: 'business',
    status: 'stable',
    route: '/carrier/reports/performance',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-dashboard', 'fuel-dashboard'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/carrier/reports.ts'],
    prismaModels: ['Load', 'Route', 'Driver'],
  },

  // ============================================================
  // OWNER PORTAL - Intelligence
  // ============================================================
  {
    slug: 'live-map',
    name: 'Live Fleet Map',
    shortDescription:
      'Real-time GPS tracking with truck status indicators, route polylines, and auto-refresh.',
    portal: 'owner',
    category: 'ai',
    planTier: 'business',
    status: 'stable',
    route: '/live-map',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['shipment-tracking'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/gps.ts'],
    prismaModels: ['GpsReport', 'Truck'],
  },
  {
    slug: 'lane-analytics',
    name: 'Lane Analytics',
    shortDescription:
      'Profitability analysis by origin-destination lane with revenue, expenses, and margin trends.',
    portal: 'owner',
    category: 'ai',
    planTier: 'business',
    status: 'stable',
    route: '/lane-analytics',
    addedInVersion: '3.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['profit-predictor', 'carrier-reports-revenue'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/lane-analytics.ts'],
    prismaModels: ['Route', 'Load'],
  },
  {
    slug: 'profit-predictor',
    name: 'AI Profit Predictor',
    shortDescription:
      'AI-powered load profitability analysis with Accept/Caution/Reject recommendations and historical lane data.',
    portal: 'owner',
    category: 'ai',
    planTier: 'business',
    status: 'stable',
    route: '/profit-predictor',
    addedInVersion: '3.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['lane-analytics', 'carrier-loads'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/profit-predictor.ts'],
    prismaModels: ['Load'],
  },

  // ============================================================
  // OWNER PORTAL - Workflows
  // ============================================================
  {
    slug: 'checklists',
    name: 'Checklists & Workflows',
    shortDescription:
      'Create and manage checklists and workflows for onboarding, inspections, and operational procedures.',
    portal: 'owner',
    category: 'workflows',
    planTier: 'pro',
    status: 'stable',
    route: '/checklists',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['playbook-builder', 'workflow-automation', 'driver-tasks'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/checklists.ts'],
    prismaModels: ['Checklist', 'ActiveChecklist'],
  },
  {
    slug: 'playbook-builder',
    name: 'Playbook Builder',
    shortDescription:
      'Visual playbook editor with drag-and-drop phases, step templates, and conditional logic.',
    portal: 'owner',
    category: 'workflows',
    planTier: 'business',
    status: 'stable',
    route: '/checklists/playbooks',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['checklists', 'workflow-automation'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/checklists.ts'],
    prismaModels: ['Checklist'],
  },
  {
    slug: 'workflow-automation',
    name: 'Workflow Automation',
    shortDescription:
      'Trigger-based automation rules to auto-start workflows on load dispatch, driver invite, and truck creation.',
    portal: 'owner',
    category: 'workflows',
    planTier: 'business',
    status: 'stable',
    route: '/checklists/automation',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['checklists', 'playbook-builder'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/automation.ts'],
    prismaModels: ['AutoStartRule'],
  },
  {
    slug: 'workflow-analytics',
    name: 'Workflow Analytics',
    shortDescription:
      'Completion metrics, bottleneck detection, and task duration analysis for active workflows.',
    portal: 'owner',
    category: 'workflows',
    planTier: 'business',
    status: 'stable',
    route: '/checklists/analytics',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['checklists'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/checklists.ts'],
    prismaModels: ['ActiveChecklist', 'Task'],
  },

  // ============================================================
  // OWNER PORTAL - Business
  // ============================================================
  {
    slug: 'ai-document-reader',
    name: 'AI Document Reader',
    shortDescription:
      'Anthropic Claude-powered extraction of structured data from rate confirmations, BOLs, and load tenders.',
    portal: 'owner',
    category: 'ai',
    planTier: 'business',
    status: 'stable',
    route: '/ai-documents',
    addedInVersion: '3.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-loads'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/documents/ai-reader.ts'],
    prismaModels: ['Document'],
  },

  // ============================================================
  // OWNER PORTAL - Finance
  // ============================================================
  {
    slug: 'invoices',
    name: 'Invoicing',
    shortDescription:
      'Trucking-standard invoicing with freight details, FSC calculation, typed line items, and PDF generation.',
    portal: 'owner',
    category: 'finance',
    planTier: 'pro',
    status: 'stable',
    route: '/invoices',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-loads', 'carrier-reports-revenue'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/invoices.ts'],
    prismaModels: ['Invoice', 'InvoiceItem'],
  },
  {
    slug: 'payroll',
    name: 'Payroll Management',
    shortDescription:
      'Driver payroll with base pay, bonuses, deductions, miles logged, and PDF payslip generation.',
    portal: 'owner',
    category: 'finance',
    planTier: 'business',
    status: 'stable',
    route: '/payroll',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-reports-driver-pay'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/payroll.ts'],
    prismaModels: ['PayrollRecord'],
  },
  {
    slug: 'fuel-dashboard',
    name: 'Fuel Economy Tracking',
    shortDescription:
      'Fuel fill-up logging with MPG trends, cost-per-mile analysis, and truck-level fuel efficiency.',
    portal: 'owner',
    category: 'finance',
    planTier: 'pro',
    status: 'stable',
    route: '/fuel',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['ifta-reporting', 'carrier-reports-performance'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/fuel.ts'],
    prismaModels: ['FuelLog'],
  },

  // ============================================================
  // OWNER PORTAL - Compliance
  // ============================================================
  {
    slug: 'compliance-dashboard',
    name: 'Compliance Dashboard',
    shortDescription:
      'Document expiry tracking for trucks and drivers with automated email reminders and compliance scores.',
    portal: 'owner',
    category: 'compliance',
    planTier: 'pro',
    status: 'stable',
    route: '/compliance',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['driver-documents', 'trucks'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/compliance.ts'],
    prismaModels: ['Document', 'Driver', 'Truck'],
  },
  {
    slug: 'ifta-reporting',
    name: 'IFTA Reporting',
    shortDescription:
      'International Fuel Tax Agreement quarterly reporting with GPS-based state mileage and fuel allocation.',
    portal: 'owner',
    category: 'compliance',
    planTier: 'business',
    status: 'stable',
    route: '/ifta',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['fuel-dashboard'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/ifta.ts'],
    prismaModels: ['GpsReport', 'FuelLog'],
  },

  // ============================================================
  // OWNER PORTAL - Settings
  // ============================================================
  {
    slug: 'team-permissions',
    name: 'Team Permissions',
    shortDescription:
      'RBAC team management with granular permissions, manager role configuration, and driver invitations.',
    portal: 'owner',
    category: 'settings',
    planTier: 'business',
    status: 'stable',
    route: '/settings/team-permissions',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['drivers'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/settings/team.ts'],
    prismaModels: ['User'],
  },
  {
    slug: 'subscription',
    name: 'Subscription Management',
    shortDescription:
      'Plan management with tier selection, billing history, and feature availability.',
    portal: 'owner',
    category: 'settings',
    planTier: 'free',
    status: 'stable',
    route: '/subscription',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: [],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/settings/subscription.ts'],
    prismaModels: ['Tenant'],
  },
  {
    slug: 'expense-categories',
    name: 'Expense Categories',
    shortDescription:
      'Configure custom expense categories for fuel, maintenance, tolls, and other operational costs.',
    portal: 'owner',
    category: 'settings',
    planTier: 'pro',
    status: 'stable',
    route: '/settings/expense-categories',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['expense-templates'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/settings/expenses.ts'],
    prismaModels: ['ExpenseCategory'],
  },
  {
    slug: 'expense-templates',
    name: 'Expense Templates',
    shortDescription:
      'Recurring expense templates for predictable costs like insurance, leases, and subscriptions.',
    portal: 'owner',
    category: 'settings',
    planTier: 'pro',
    status: 'stable',
    route: '/settings/expense-templates',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['expense-categories'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/settings/expenses.ts'],
    prismaModels: ['ExpenseTemplate'],
  },
  {
    slug: 'integrations',
    name: 'Third-Party Integrations',
    shortDescription:
      'Connect QuickBooks, Samsara, Motive/KeepTruckin, factoring services, and email providers.',
    portal: 'owner',
    category: 'integrations',
    planTier: 'business',
    status: 'stable',
    route: '/settings/integrations',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: [],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/settings/integrations.ts'],
    prismaModels: ['Tenant'],
  },

  // ============================================================
  // OWNER PORTAL - Legacy/CRM
  // ============================================================
  {
    slug: 'trucks',
    name: 'Legacy Truck Management',
    shortDescription:
      'Truck management with VIN, make, model, documents, maintenance history, and status badges.',
    portal: 'owner',
    category: 'fleet',
    planTier: 'pro',
    status: 'stable',
    route: '/trucks',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-fleet-trucks'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/trucks.ts'],
    prismaModels: ['Truck', 'Document', 'ScheduledService'],
  },
  {
    slug: 'drivers',
    name: 'Legacy Driver Management',
    shortDescription:
      'Driver profiles, invitations via email, document tracking, and safety scores.',
    portal: 'owner',
    category: 'fleet',
    planTier: 'pro',
    status: 'stable',
    route: '/drivers',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-fleet-drivers'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/drivers.ts'],
    prismaModels: ['Driver', 'User', 'DriverInvitation'],
  },
  {
    slug: 'routes',
    name: 'Route Planning',
    shortDescription:
      'Multi-stop route creation with leg sequencing, continuity warnings, and driver assignment.',
    portal: 'owner',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/routes',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-loads', 'driver-my-route'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/routes.ts'],
    prismaModels: ['Route', 'RouteStop'],
  },
  {
    slug: 'loads',
    name: 'Legacy Load Management',
    shortDescription:
      'Load CRUD with status workflow, customer assignment, and tracking token generation.',
    portal: 'owner',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/loads',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-loads'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/loads.ts'],
    prismaModels: ['Load', 'RouteStop'],
  },
  {
    slug: 'crm',
    name: 'Customer Relationship Management',
    shortDescription:
      'Customer and contact management with load history, revenue totals, and interaction logging.',
    portal: 'owner',
    category: 'crm',
    planTier: 'pro',
    status: 'stable',
    route: '/crm',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-clients'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/crm.ts'],
    prismaModels: ['Customer', 'CustomerInteraction'],
  },
  {
    slug: 'safety-analytics',
    name: 'Safety Analytics',
    shortDescription:
      'Driver safety scoring with harsh braking, speeding events, and safety trend charts.',
    portal: 'owner',
    category: 'compliance',
    planTier: 'business',
    status: 'stable',
    route: '/safety',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['driver-incidents'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/safety.ts'],
    prismaModels: ['SafetyEvent'],
  },
  {
    slug: 'tags',
    name: 'Tags & Labels',
    shortDescription:
      'Color-coded labels for organizing trucks and drivers with filtering and grouping.',
    portal: 'owner',
    category: 'settings',
    planTier: 'free',
    status: 'stable',
    route: '/tags',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: [],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/tags.ts'],
    prismaModels: ['Tag'],
  },
  {
    slug: 'help-center',
    name: 'Help Center',
    shortDescription:
      'In-app documentation hub with feature guides, video tutorials, and what\'s new updates.',
    portal: 'owner',
    category: 'support',
    planTier: 'free',
    status: 'stable',
    route: '/help',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: [],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: [],
    prismaModels: [],
  },

  // ============================================================
  // DRIVER PORTAL
  // ============================================================
  {
    slug: 'driver-dashboard',
    name: 'Driver Dashboard',
    shortDescription:
      'Driver home screen with active load card, stat chips, alerts, and My Route shortcut.',
    portal: 'driver',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/home',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['driver-my-load', 'driver-my-route'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/dashboard/route.ts'],
    prismaModels: ['Load', 'Route'],
  },
  {
    slug: 'driver-my-load',
    name: 'Driver My Load',
    shortDescription:
      'Current load status management with forward-only status advancement and stop timeline.',
    portal: 'driver',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/my-load',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-loads', 'driver-my-route'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/loads/route.ts'],
    prismaModels: ['Load', 'RouteStop'],
  },
  {
    slug: 'driver-my-route',
    name: 'Driver My Route',
    shortDescription:
      'Route view with loads timeline, truck info, route-scoped messages, and stop details.',
    portal: 'driver',
    category: 'dispatch',
    planTier: 'pro',
    status: 'stable',
    route: '/my-route',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['routes', 'driver-my-load'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/routes/route.ts'],
    prismaModels: ['Route', 'Load', 'RouteStop'],
  },
  {
    slug: 'driver-hours',
    name: 'Hours of Service',
    shortDescription:
      'HOS logging with 14h/11h duty clock math, status grid, day bar, and countdown timers.',
    portal: 'driver',
    category: 'compliance',
    planTier: 'pro',
    status: 'stable',
    route: '/hours',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: [],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/hos/route.ts'],
    prismaModels: ['DriverHOSEntry'],
  },
  {
    slug: 'driver-incidents',
    name: 'Incident Reporting',
    shortDescription:
      'Incident reporting with photo capture, severity toggle, category selection, and timestamp.',
    portal: 'driver',
    category: 'compliance',
    planTier: 'pro',
    status: 'stable',
    route: '/incidents',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['safety-analytics'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/incidents/route.ts'],
    prismaModels: ['DriverIncident'],
  },
  {
    slug: 'driver-messages',
    name: 'Driver Messaging',
    shortDescription:
      'Load-scoped messaging with owner/dispatcher, unread badges, and 30s polling.',
    portal: 'driver',
    category: 'fleet',
    planTier: 'pro',
    status: 'stable',
    route: '/messages',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['carrier-messages'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/messages/route.ts'],
    prismaModels: ['FleetMessage'],
  },
  {
    slug: 'driver-tasks',
    name: 'Driver Workflow Tasks',
    shortDescription:
      'Workflow task completion with checklist progression, step instructions, and photo attachments.',
    portal: 'driver',
    category: 'workflows',
    planTier: 'pro',
    status: 'stable',
    route: '/tasks',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['checklists'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/tasks/route.ts'],
    prismaModels: ['Task', 'ActiveChecklist'],
  },
  {
    slug: 'driver-documents',
    name: 'Driver Documents',
    shortDescription:
      'Document upload/view with R2 presigned URLs, expiry tracking, and compliance status.',
    portal: 'driver',
    category: 'compliance',
    planTier: 'pro',
    status: 'stable',
    route: '/documents',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['compliance-dashboard'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/mobile/driver/documents/route.ts'],
    prismaModels: ['Document'],
  },

  // ============================================================
  // ADMIN PORTAL
  // ============================================================
  {
    slug: 'tenant-management',
    name: 'Tenant Management',
    shortDescription:
      'Multi-tenant administration with creation, status controls, and owner invitation flow.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/tenants',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['admin-billing'],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/admin/tenants.ts'],
    prismaModels: ['Tenant', 'User'],
  },
  {
    slug: 'admin-support',
    name: 'SysAdmin Support Queue',
    shortDescription:
      'Cross-tenant support ticket queue with status filtering, AI suggestions, and reply threads.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/admin-support',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['support-tickets'],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/admin/support.ts'],
    prismaModels: ['SupportTicket'],
  },
  {
    slug: 'admin-billing',
    name: 'SysAdmin Billing',
    shortDescription:
      'DriveCommand-to-tenant invoicing with line items, email delivery, and overdue cron.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/billing',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['tenant-management'],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/admin/billing.ts'],
    prismaModels: ['SysAdminInvoice', 'SysAdminInvoiceItem'],
  },
  {
    slug: 'admin-plans',
    name: 'Subscription Plan Management',
    shortDescription:
      'Configure subscription plans with pricing, features, and billing intervals.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/plans',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['subscription'],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/admin/plans.ts'],
    prismaModels: ['SubscriptionPlan'],
  },
  {
    slug: 'admin-promos',
    name: 'Promotional Code Management',
    shortDescription:
      'Create and manage promo codes with discounts, expiry dates, and usage limits.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/promos',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['admin-billing'],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/admin/promos.ts'],
    prismaModels: ['PromoCode'],
  },
  {
    slug: 'admin-automations',
    name: 'Platform Automation Rules',
    shortDescription:
      'Platform-wide automation rules for trial reminders, engagement nudges, and billing alerts.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/automations',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: [],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/admin/automations.ts'],
    prismaModels: ['AutomationRule'],
  },
  {
    slug: 'admin-docs',
    name: 'SysAdmin Knowledge Base',
    shortDescription:
      'Technical knowledge base with feature reference, operations docs, and admin search.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/docs',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: [],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: [],
    prismaModels: [],
  },
  {
    slug: 'admin-dashboard',
    name: 'Platform Metrics Dashboard',
    shortDescription:
      'Platform health metrics with total tenants, active users, and system status.',
    portal: 'admin',
    category: 'admin',
    planTier: 'enterprise',
    status: 'stable',
    route: '/admin-dashboard',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['tenant-management'],
    requiresClientDoc: false,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/admin/dashboard.ts'],
    prismaModels: ['Tenant', 'User'],
  },

  // ============================================================
  // SHARED
  // ============================================================
  {
    slug: 'support-tickets',
    name: 'Support Tickets',
    shortDescription:
      'In-app support ticket system with screenshot capture, file attachments, and message threads.',
    portal: 'shared',
    category: 'support',
    planTier: 'free',
    status: 'stable',
    route: '/support',
    addedInVersion: '2.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['admin-support'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/actions/support.ts'],
    prismaModels: ['SupportTicket'],
  },
  {
    slug: 'shipment-tracking',
    name: 'Public Shipment Tracking',
    shortDescription:
      'Public tracking page accessible via unique token with GPS map, status timeline, and ETA.',
    portal: 'shared',
    category: 'support',
    planTier: 'pro',
    status: 'stable',
    route: '/track/[token]',
    addedInVersion: '1.0.0',
    lastDocReviewedAt: '2026-05-09T00:00:00Z',
    relatedFeatureSlugs: ['live-map', 'carrier-loads'],
    requiresClientDoc: true,
    requiresSysadminDoc: true,
    serverActionPaths: ['src/app/api/track/route.ts'],
    prismaModels: ['Load', 'GpsReport'],
  },
] as const;

// First-pass validation: Zod schema for all fields
const parsedFeatures = z.array(FeatureSchema).parse(rawFeatures);

// Second-pass validation: Check relatedFeatureSlugs references
const validSlugs = new Set(parsedFeatures.map((f) => f.slug));
const brokenReferences: Array<{ feature: string; invalidSlug: string }> = [];

for (const feature of parsedFeatures) {
  for (const relatedSlug of feature.relatedFeatureSlugs) {
    if (!validSlugs.has(relatedSlug)) {
      brokenReferences.push({
        feature: feature.slug,
        invalidSlug: relatedSlug,
      });
    }
  }
}

if (brokenReferences.length > 0) {
  const errorMessage = [
    'Invalid relatedFeatureSlugs references found:',
    ...brokenReferences.map(
      (ref) => `  - Feature "${ref.feature}" references non-existent slug "${ref.invalidSlug}"`
    ),
  ].join('\n');
  throw new Error(errorMessage);
}

export const features: Feature[] = parsedFeatures;
