'use server';

import { getSession } from '@/lib/auth/supabase';
import { createRouteTemplate, updateRouteTemplate } from '@/lib/carrier/route-templates';
import { prisma } from '@/lib/db/prisma';
import type { StopBuilderStop } from '@/components/carrier/stops/StopCard';

export interface SaveRouteTemplateInput {
  templateId?: string;
  templateName: string;
  clientId: string;
  contractId?: string;
  scheduleType: string;
  recurrenceRule?: string;
  recurrenceTimezone?: string;
  scheduledDepartureTime?: string;
  equipmentType: string;
  tempMinF?: number;
  tempMaxF?: number;
  maxWeightLbs?: number;
  commodityDescription?: string;
  defaultDriverId?: string;
  defaultTruckId?: string;
  autoGenerateDaysAhead?: number;
  notes?: string;
  stops: StopBuilderStop[];
}

export interface SaveRouteTemplateResult {
  success: boolean;
  templateId?: string;
  error?: string;
}

export async function saveRouteTemplate(
  data: SaveRouteTemplateInput
): Promise<SaveRouteTemplateResult> {
  try {
    const session = await getSession();
    if (!session) return { success: false, error: 'Unauthorized' };
    const orgId = session.tenantId;
    if (!orgId) return { success: false, error: 'No organization' };

    const {
      templateId,
      templateName,
      clientId,
      contractId,
      scheduleType,
      recurrenceRule,
      recurrenceTimezone,
      scheduledDepartureTime,
      equipmentType,
      tempMinF,
      tempMaxF,
      maxWeightLbs,
      commodityDescription,
      defaultDriverId,
      defaultTruckId,
      autoGenerateDaysAhead,
      notes,
      stops,
    } = data;

    // Validate required fields
    if (!templateName.trim()) return { success: false, error: 'Template name is required' };
    if (!clientId) return { success: false, error: 'Client is required' };
    if (!equipmentType) return { success: false, error: 'Equipment type is required' };
    if (!scheduleType) return { success: false, error: 'Schedule type is required' };
    if (recurrenceRule && !recurrenceRule.startsWith('FREQ=')) {
      return { success: false, error: 'Recurrence rule must start with FREQ=' };
    }
    if (stops.length === 0) return { success: false, error: 'At least one stop is required' };

    // Build template payload — only include optional fields if set
    const templateData = {
      templateName: templateName.trim(),
      clientId,
      scheduleType,
      equipmentType,
      ...(contractId ? { contractId } : {}),
      ...(recurrenceRule ? { recurrenceRule } : {}),
      ...(recurrenceTimezone ? { recurrenceTimezone } : {}),
      ...(scheduledDepartureTime ? { scheduledDepartureTime } : {}),
      ...(tempMinF != null ? { tempMinF } : {}),
      ...(tempMaxF != null ? { tempMaxF } : {}),
      ...(maxWeightLbs != null ? { maxWeightLbs } : {}),
      ...(commodityDescription ? { commodityDescription } : {}),
      ...(defaultDriverId ? { defaultDriverId } : {}),
      ...(defaultTruckId ? { defaultTruckId } : {}),
      ...(autoGenerateDaysAhead != null ? { autoGenerateDaysAhead } : {}),
      ...(notes ? { notes } : {}),
    };

    // Map StopBuilderStop → RouteTemplateStop DB fields
    const stopData = stops.map((stop) => ({
      facilityId: stop.facility_id,
      sequenceOrder: stop.sequence_order,
      stopType: stop.stop_type,
      contactName: stop.contact_name,
      contactPhone: stop.contact_phone,
      apptWindowStartOffsetMin: stop.appt_window_start_offset_min,
      apptWindowEndOffsetMin: stop.appt_window_end_offset_min,
      expectedDwellMinutes: stop.expected_dwell_minutes,
      commodityDescription: stop.commodity_description,
      bolRequired: stop.bol_required,
      podRequired: stop.pod_required,
      specialInstructions: stop.special_instructions,
    }));

    if (templateId) {
      // Edit mode: update template + replace stops in a transaction
      const existing = await prisma.routeTemplate.findFirst({ where: { id: templateId, orgId } });
      if (!existing) return { success: false, error: 'Template not found' };

      await prisma.$transaction([
        prisma.routeTemplate.update({
          where: { id: templateId },
          data: templateData,
        }),
        prisma.routeTemplateStop.deleteMany({ where: { routeTemplateId: templateId } }),
        ...stopData.map((s) =>
          prisma.routeTemplateStop.create({
            data: { routeTemplateId: templateId, ...s },
          })
        ),
      ]);

      return { success: true, templateId };
    } else {
      // Create mode: create template then stops in a transaction
      const result = await prisma.$transaction(async (tx) => {
        const template = await tx.routeTemplate.create({
          data: { orgId, ...templateData },
        });

        if (stopData.length > 0) {
          await tx.routeTemplateStop.createMany({
            data: stopData.map((s) => ({ routeTemplateId: template.id, ...s })),
          });
        }

        return template;
      });

      return { success: true, templateId: result.id };
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unexpected error';
    return { success: false, error: message };
  }
}
