'use server';

/**
 * The Templates screen's save action.
 *
 * The body of this function moved to `lib/carrier/route-template-save.ts` when
 * document import (Phase 6) needed the same write from a Bearer-token request
 * with no session cookie and no `x-tenant-id` header. Nothing about what it does
 * changed — this is the same validation, the same messages and the same
 * transaction, reached through the shared core so there is one save path rather
 * than two that agree today.
 */

import { getSession } from '@/lib/auth/supabase';
import { getTenantPrisma } from '@/lib/context/tenant-context';
import {
  saveRouteTemplateCore,
  type SaveRouteTemplateOutcome,
} from '@/lib/carrier/route-template-save';
import type { StopBuilderStop } from '@/components/carrier/stops/StopCard';

export interface SaveRouteTemplateInput {
  templateId?: string;
  templateName: string;
  clientId: string;
  contractId?: string;
  scheduleType: string;
  recurrenceRule?: string;
  recurrenceTimezone?: string;
  scheduledDepartureTime?: string;
  equipmentType: string;
  tempMinF?: number;
  tempMaxF?: number;
  maxWeightLbs?: number;
  commodityDescription?: string;
  defaultDriverId?: string;
  defaultTruckId?: string;
  autoGenerateDaysAhead?: number;
  notes?: string;
  stops: StopBuilderStop[];
}

export type SaveRouteTemplateResult = SaveRouteTemplateOutcome;

export async function saveRouteTemplate(
  data: SaveRouteTemplateInput
): Promise<SaveRouteTemplateResult> {
  try {
    const session = await getSession();
    if (!session) return { success: false, error: 'Unauthorized' };
    const orgId = session.tenantId;
    if (!orgId) return { success: false, error: 'No organization' };

    const tenantPrisma = await getTenantPrisma();
    return await saveRouteTemplateCore(tenantPrisma, orgId, data);
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unexpected error';
    return { success: false, error: message };
  }
}
